### ISSUE TITLE
[Bug?]: Error setting up new project

### ISSUE THREAD

**Issue by Lastofthefirst** [solidjs/solid-start#1016]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I create a new solidstart project using the tailwind template, and no typescript, I get the following error on trying to run `npm run dev -- --open`:

```
file:///Users/idealmine/Documents/Ridvan/biz-card/node_modules/.pnpm/solid-start@0.3.3_@solidjs+meta@0.28.5_@solidjs+router@0.8.2_solid-js@1.7.11_solid-start-node@0.3.0_vite@4.4.6/node_modules/solid-start/node/fetch.js:73
export class NodeRequest extends Request {
                                 ^

ReferenceError: Request is not defined
    at file:///Users/idealmine/Documents/Ridvan/biz-card/node_modules/.pnpm/solid-start@0.3.3_@solidjs+meta@0.28.5_@solidjs+router@0.8.2_solid-js@1.7.11_solid-start-node@0.3.0_vite@4.4.6/node_modules/solid-start/node/fetch.js:73:34
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async file:///Users/idealmine/Documents/Ridvan/biz-card/node_modules/.pnpm/solid-start@0.3.3_@solidjs+meta@0.28.5_@solidjs+router@0.8.2_solid-js@1.7.11_solid-start-node@0.3.0_vite@4.4.6/node_modules/solid-start/vite/plugin.js:532:38

Node.js v17.3.0
```

### Expected behavior 🤔

The app should be served to localhost:3000

### Your environment 🌎

```shell
Software:

    System Software Overview:

      System Version: macOS 13.2.1 (22D68)
      Kernel Version: Darwin 22.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Quddus’s MacBook Pro
      User Name: Quddus George (idealmine)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 5 days, 19 hours, 50 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2.2 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 9 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      System Firmware Version: 1916.80.2.0.0 (iBridge: 20.16.3045.0.0,0)
      OS Loader Version: 564.40.4~66
      Serial Number (system): C02XF0QLJGH7
      Hardware UUID: 1CF49A31-E908-5918-BED6-2C16854F45F0
      Provisioning UDID: 1CF49A31-E908-5918-BED6-2C16854F45F0
      Activation Lock Status: Disabled
```

**Comment by edivados** [comment]
[`0.3.x`](https://github.com/solidjs/solid-start/releases/tag/v0.3.1) changed base version to Node 18.

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
