### ISSUE TITLE
[Bug]: Solid Start Build fails to parse jsx files

### ISSUE THREAD

**Issue by wakaztahir** [solidjs/solid-start#1080]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Error [RollupError]: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.tryParse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:14476:25)
    at Module.setSource (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:14077:39)
    at ModuleLoader.addModuleSource (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:24649:20) {
  cause: SyntaxError: Unexpected token (3:9)
      at pp$4.raise (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:21621:13)
      at pp$9.unexpected (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18829:8)
      at pp$5.parseExprAtomDefault (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20990:8)
      at pp$5.parseExprAtom (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20985:17)
      at pp$5.parseExprSubscripts (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20769:19)
      at pp$5.parseMaybeUnary (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20735:17)
      at pp$5.parseExprOps (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20662:19)
      at pp$5.parseMaybeConditional (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20645:19)
      at pp$5.parseMaybeAssign (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20612:19)
      at pp$5.parseExpression (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:20575:19)
      at pp$8.parseReturnStatement (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:19149:31)
      at pp$8.parseStatement (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18977:37)
      at pp$8.parseBlock (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:19311:21)
      at pp$5.parseFunctionBody (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:21440:22)
      at pp$8.parseFunction (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:19433:8)
      at pp$8.parseFunctionStatement (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:19127:15)
      at pp$8.parseStatement (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18972:17)
      at pp$8.parseTopLevel (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18886:21)
      at Parser.parse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18658:15)
      at Function.parse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:18708:35)
      at Graph.contextParse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:25754:38)
      at Module.tryParse (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:14473:31)
      at Module.setSource (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:14077:39)
      at ModuleLoader.addModuleSource (file:///D:/Programming/Web/Libraries/solid-account-management/node_modules/rollup/dist/es/shared/node-entry.js:24649:20) {
    pos: 53,
    loc: Position { line: 3, column: 9 },
    raisedAt: 54
  },
  code: 'PARSE_ERROR',
  id: 'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\anique-icons\\dist\\server.jsx',
  pos: 53,
  loc: {
    column: 9,
    file: 'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\anique-icons\\dist\\server.jsx',
    line: 3
  },
  frame: '1: // src/AlertIcon.tsx\n' +
    '2: function AlertIcon() {\n' +
    '3:   return <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">\n' +
    '            ^\n' +
    '4:     <title>alert</title>\n' +
    '5:     <path d="M13 14H11V9H13M13 18H11V16H13M1 21H23L12 2L1 21Z" />',
  watchFiles: [
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\demo\\.solid\\server\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\demo\\.solid\\server\\entry-server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\demo\\dist\\public\\route-manifest.json',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\solid-start\\node\\globals.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\solid-start\\node\\fetch.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\solid-js\\dist\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\solid-js\\web\\dist\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\anique\\dist\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\typescript-cookie\\dist\\typescript-cookie.mjs',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\emotion\\dist\\server.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\seroval\\dist\\esm\\production\\index.mjs',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@qinetik\\anique-icons\\dist\\server.jsx',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@emotion\\is-prop-valid\\dist\\emotion-is-prop-valid.esm.js',
    'D:\\Programming\\Web\\Libraries\\solid-account-management\\node_modules\\@emotion\\serialize\\dist\\emotion-serialize.esm.js'
  ]
}

### Expected behavior 🤔

The build should succeed

### Steps to reproduce 🕹

Steps:

1. I am using @qinetik/anique-icons package in my project

**Comment by wakaztahir** [comment]
I found it in this issue as well, but that's completely differnet
https://github.com/solidjs/solid-start/issues/822#issuecomment-1686666730

anique-icons is built using the package tsup-preset-solid
