### ISSUE TITLE
[Bug?]: Route does not load when it should

### ISSUE THREAD

**Issue by nikitavoloboev** [solidjs/solid-start#1194]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Started with `npm init solid@latest`, using file routes:

<img width="1036" alt="image" src="https://github.com/solidjs/solid-start/assets/6391776/edb6d43e-d319-496d-87b9-129c9a1f7c47">

I have a file route `now.tsx`:

<img width="785" alt="image" src="https://github.com/solidjs/solid-start/assets/6391776/0edbcfc4-db14-4c8a-88c4-58088c0e2f06">

But when I run project and go to the route, nothing happens:

<img width="1125" alt="image" src="https://github.com/solidjs/solid-start/assets/6391776/0bf778eb-81da-4188-9a67-43a3db6a4677">

Replication code: https://github.com/nikitavoloboev/try/tree/main/solid-start-beta-2

I am trying to migrate [my solid start 1 personal website](https://github.com/nikitavoloboev/nikiv.dev) to new version but this is a major blocker.

### Expected behavior 🤔

Route renders.

**Comment by brenelz** [comment]
I just tried your replication repo and the /now route seems to render fine

**Comment by nikitavoloboev** [comment]
I am now getting this:

<img width="584" alt="image" src="https://github.com/solidjs/solid-start/assets/6391776/29905777-1b9c-452d-ac11-067b7de134f9">

In text:

```

  ➜  API Routes:
     None! 👻

🔥 GET http://localhost:3000/
TypeError: Comp is not a function
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:39:48)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:32:20)
    at error (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:457:26)
    at catchError (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:152:12)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:456:12
    at createMemo (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:95:9)
    at ErrorBoundary (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:454:3)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at ErrorBoundary (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:15:32)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:37:44)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:685:41
    at catchError (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:152:12)
    at get children [as children] (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:685:18)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:216:35
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:179:49
    at createMemo (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:95:9)
    at children (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:179:16)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:216:14
    at createMemo (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:95:9)
    at provider (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:211:12)
    at createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:682:7
    at runWithOwner (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:190:12)
    at runSuspense (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:681:12)
    at Suspense (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:690:15)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:35:41)
    at eval (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/root/Document.tsx:39:111)
    at Proxy.ssrElement (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/web/dist/server.js:421:50)
    at Body (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/root/Document.tsx:39:34)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:32:33)
    at Proxy.ssrElement (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/web/dist/server.js:393:69)
    at Html (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/root/Document.tsx:22:34)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at Root (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:15:32)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/entry-server/StartServer.tsx:99:54)
    at eval (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/@solidjs+router@0.10.5_solid-js@1.8.7/node_modules/@solidjs/router/dist/routers/components.jsx:18:64)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:179:49
    at createMemo (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:95:9)
    at Proxy.children (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:179:16)
    at eval (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/@solidjs+router@0.10.5_solid-js@1.8.7/node_modules/@solidjs/router/dist/routers/components.jsx:18:43)
    at Module.StaticRouter (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/@solidjs+router@0.10.5_solid-js@1.8.7/node_modules/@solidjs/router/dist/routers/StaticRouter.js:18:7)
    at Router (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/@solidjs+router@0.10.5_solid-js@1.8.7/node_modules/@solidjs/router/dist/routers/Router.js:13:38)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at StartRouter (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/entry-server/StartServer.tsx:67:32)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
🔥 GET http://localhost:3000/now
TypeError: Comp is not a function
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:39:48)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:32:20)
    at error (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:457:26)
    at catchError (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:152:12)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:456:12
    at createMemo (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:95:9)
    at ErrorBoundary (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:454:3)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at ErrorBoundary (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:15:32)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:37:44)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:685:41
    at catchError (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:152:12)
    at get children [as children] (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:685:18)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:216:35
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:179:49
    at createMemo (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:95:9)
    at children (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:179:16)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:216:14
    at createMemo (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:95:9)
    at provider (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:211:12)
    at createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:682:7
    at runWithOwner (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:190:12)
    at runSuspense (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:681:12)
    at Suspense (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:690:15)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:35:41)
    at eval (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/root/Document.tsx:39:111)
    at Proxy.ssrElement (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/web/dist/server.js:421:50)
    at Body (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/root/Document.tsx:39:34)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:32:33)
    at Proxy.ssrElement (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/web/dist/server.js:393:69)
    at Html (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/root/Document.tsx:22:34)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at Root (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:15:32)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/entry-server/StartServer.tsx:99:54)
    at eval (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/@solidjs+router@0.10.5_solid-js@1.8.7/node_modules/@solidjs/router/dist/routers/components.jsx:18:64)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:179:49
    at createMemo (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:95:9)
    at Proxy.children (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:179:16)
    at eval (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/@solidjs+router@0.10.5_solid-js@1.8.7/node_modules/@solidjs/router/dist/routers/components.jsx:18:43)
    at Module.StaticRouter (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/@solidjs+router@0.10.5_solid-js@1.8.7/node_modules/@solidjs/router/dist/routers/StaticRouter.js:18:7)
    at Router (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/@solidjs+router@0.10.5_solid-js@1.8.7/node_modules/@solidjs/router/dist/routers/Router.js:13:38)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at StartRouter (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/entry-server/StartServer.tsx:67:32)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
🔥 GET http://localhost:3000/now
TypeError: Comp is not a function
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/src/root.jsx:39:48)
    at get children [as children] (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:32:20)
    at error (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:457:26)
    at catchError (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:152:12)
    at file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:456:12
    at createMemo (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:95:9)
    at ErrorBoundary (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:454:3)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    at ErrorBoundary (/Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.3_@solidjs+router@0.10.5_solid-js@1.8.7_solid-start-clo_opu367g4rm3cbhejxs7lvdxlc4/node_modules/solid-start/error-boundary/ErrorBoundary.tsx:15:32)
    at Proxy.createComponent (file:///Users/nikiv/src/sites/nikiv.dev/node_modules/.pnpm/solid-js@1.8.7/node_modules/solid-js/dist/server.js:349:15)
    ```

**Comment by brenelz** [comment]
Are you sure thats the right project? That looks like solid start beta 1

**Comment by nikitavoloboev** [comment]
> Are you sure thats the right project?

You are right, made mistake.

Here is what I see for the project that has error and is solid beta 2:

https://github.com/solidjs/solid-start/assets/6391776/5442eb6d-0bf0-4be2-aa27-4db112096ab7

**Comment by brenelz** [comment]
so odd... anything in the console?

**Comment by nikitavoloboev** [comment]
```
❯ 
node --version
v18.15.0
```

<img width="395" alt="image" src="https://github.com/solidjs/solid-start/assets/6391776/07c98791-d9a5-48e1-b13f-207b0add64c1">

Above is all I see even after hitting `/now` route.

**Comment by brenelz** [comment]
I mean in the google chrome console

**Comment by nikitavoloboev** [comment]
<img width="643" alt="image" src="https://github.com/solidjs/solid-start/assets/6391776/ca541759-7a44-4ba1-a497-541c9f230eba">

All i see is above.

But I see it when I render the `/` route too. Which actually does show strangely.

<img width="1512" alt="image" src="https://github.com/solidjs/solid-start/assets/6391776/f6b086a4-2dd7-435b-b461-7c77edb7f73e">

**Comment by brenelz** [comment]
yeah thats fine. Maybe try incognito window?

**Comment by nikitavoloboev** [comment]
omg it works in incognito tab

<img width="955" alt="image" src="https://github.com/solidjs/solid-start/assets/6391776/281304d9-d4f8-427f-8dc0-e4392e3dd0de">

wtf

firstly thank you for the help

I guess I should clear the cache somehow for localhost now?

**Comment by brenelz** [comment]
I'm guessing some chrome extension interfering somehow

**Comment by nikitavoloboev** [comment]
Ok hard refresh worked

<img width="371" alt="image" src="https://github.com/solidjs/solid-start/assets/6391776/086accc1-f340-419a-8282-f767e15ddac2">

Thanks a lot.

**Comment by metruzanca** [comment]
I've also encountered this, and hard refresh was the solution for me too. So maybe its a HMR issue.
