### ISSUE TITLE
[Bug?]: `<HttpHeader/>` causes uncaught error

### ISSUE THREAD

**Issue by samualtnorman** [solidjs/solid-start#1253]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```
nixos% pnpm dev

> tmp.CUDbecTs89@ dev /tmp/tmp.CUDbecTs89
> vinxi dev

vinxi 0.1.2
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vinxi Found vite.config.js with app config
vinxi starting dev server

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

node:_http_outgoing:782
    throw new ERR_HTTP_HEADERS_SENT('remove');
    ^

Error: Cannot remove headers after they are sent to the client
    at ServerResponse.removeHeader (node:_http_outgoing:782:11)
    at Module.removeResponseHeader (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:763:25)
    at Array.eval (/tmp/tmp.CUDbecTs89/node_modules/.pnpm/@solidjs+start@0.4.9_solid-js@1.8.11_vinxi@0.1.2_vite@5.0.11/node_modules/@solidjs/start/server/page-event.tsx:54:135)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:132:68)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:128:49)
    at file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/dist/server.js:54:52
    at Timeout._onTimeout (file:///tmp/tmp.CUDbecTs89/node_modules/.pnpm/solid-js@1.8.11/node_modules/solid-js/web/dist/server.js:305:13)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```
```
nixos% node .output/server/index.mjs
Listening on http://[::]:3000
[nitro] [uncaughtException] Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
    at new NodeError (node:internal/errors:406:5)
    at ServerResponse.removeHeader (node:_http_outgoing:782:11)
    at removeResponseHeader (file:///tmp/tmp.CUDbecTs89/.output/server/chunks/nitro/node-server.mjs:1906:25)
    at Array.<anonymous> (file:///tmp/tmp.CUDbecTs89/.output/server/chunks/nitro/node-server.mjs:7793:91)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/.output/server/node_modules/solid-js/dist/server.js:132:68)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/.output/server/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/.output/server/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/.output/server/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/.output/server/node_modules/solid-js/dist/server.js:128:49)
    at cleanNode (file:///tmp/tmp.CUDbecTs89/.output/server/node_modules/solid-js/dist/server.js:128:49) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

### Expected behavior 🤔

it to not do that

### Steps to reproduce 🕹

Steps:

1. `pnpm create solid`
2. choose "basic"
3. `pnpm install`
4. edit `src/routes/index.tsx`
	```diff
	 import { Title } from "@solidjs/meta";
	+import { HttpHeader } from "@solidjs/start";
	 import Counter from "~/components/Counter";
 	
	 export default function Home() {
	   return (
	     <main>
	       <Title>Hello World</Title>
	+      <HttpHeader name="x-foo" value="bar"/>
	       <h1>Hello world!</h1>
	       <Counter />
	       <p>
	```
5. run `pnpm dev` and open the route in the browser

### Context 🔦

I would like to add a header to the response.

### Your environment 🌎

```shell
OS: NixOS 23.11.2774.3dc440faeee9 (Tapir) x86_64
Host: ASUS MB
Kernel: 6.1.71
Uptime: 3 hours, 58 mins
Packages: 1842 (nix-system)
Shell: zsh 5.9
Display (PL2492H): 1920x1080 @ 75Hz *
Display (PL2492H): 1920x1080 @ 60Hz
DE: KDE Plasma 5.27.10
WM: KWin (X11)
WM Theme: Breeze
Theme: Breeze (Dark) [QT]
Icons: breeze-dark [QT], breeze-dark [GTK2/3/4]
Font: Noto Sans (10pt) [QT], Noto Sans (10pt) [GTK2/3/4]
Cursor: breeze (24px)
Terminal: code 1.85.1
CPU: Intel(R) Core(TM) i5-4670K (4) @ 3.80 GHz
GPU: NVIDIA GeForce GTX 1060 6GB
Memory: 5.68 GiB / 15.57 GiB (36%)
Swap: 5.25 MiB / 17.13 GiB (0%)
Disk (/): 263.47 GiB / 898.46 GiB (29%) - ext4
Local IP (enp4s0): 10.0.0.175/16 *
Locale: en_GB.UTF-8
```

**Comment by danicruz0415** [comment]
Hi, Im not sure to have the full context but according to the HTTP spec, all headers must be sent before the body. So maybe you are using the HttpHeader inside a child route that is loaded after the stream first flushed. 

I quote from the API reference for API reference for [HttpHeader](https://start.solidjs.com/api/HttpHeader):

> Keep in mind, when streaming responses(renderStream), HTTP headers can only be included that are added before the stream first flushed. Be sure to add `deferStream` to any resources that needed to be loaded before responding.

So make sure that you add the header in a component that is processed before the page is sent to the client or take a look at `deferStream`. Hope this helps

**Comment by ryansolid** [comment]
This is correct. I guess the question is whether we should expose the fact the screen is flushed and then just skip these operations. Like is it better to have it just not happen silently?

**Comment by samualtnorman** [comment]
in dev mode, it should log a warning instead of crashing with a message on how to do what the developer is probably *trying* to do

**Comment by ryansolid** [comment]
I mean it isn't completely broken otherwise it wouldn't work in all the examples. The reported issue sounded like it had to do with streaming timing. If you have an example where it doesn't.. for example setting `ssr: "async"` I'd look at it.

I think the error is correct if we should error.  We wouldn't handle it differently between prod and dev. The dev server crashing is on the dev server, so that would be a different issue.  The question is would it be better to always warn or always error (assuming the dev server wouldn't crash on an error).
