### ISSUE TITLE
[Bug?]: dev server crashing

### ISSUE THREAD

**Issue by sysmat** [solidjs/solid-start#1256]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

- I have API route
- I have client component to list items
- I have route page to which use component

### Expected behavior 🤔

- server not to crashing

### Steps to reproduce 🕹

Steps:

1. https://stackblitz.com/~/github.com/sysmat/stackblitz-solid-start-04.9
2. in terminal go to `cd my-app`
3.  install `pnpm i`
4. run dev `pnpm dev`
5. In app use Reservation link to go to page
6. wait a  seconds and server crash

```
 - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new
        at new G (/home/sysmat/stackblitz-solid-start-04.9/my-app/node_modules/.pnpm/seroval@1.0.4/node_modules/seroval/dist/esm/production/index.mjs:57:116)
        ... 8 lines matching cause stack trace ...
        at J.parseObject (/home/sysmat/stackblitz-solid-start-04.9/my-app/node_modules/.pnpm/seroval@1.0.4/node_modules/seroval/dist/esm/production/index.mjs:61:31307) {
      cause: [j]
    }
  }
}
```

### Your environment 🌎

```shell
web container on stackblitz
```

**Comment by lxsmnsyc** [comment]
You've trimmed the error log. Please show the full log.

Also, can't test the stackblitz you shared, it shows "Upgrade Required"

**Comment by sysmat** [comment]
- hm, strange from stackblitz
- @lxsmnsyc can you fork stackblitz project?

```

          - For more information, please check the "cause" property of this error.
          - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new

          - For more information, please check the "cause" property of this error.
          - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new

          - For more information, please check the "cause" property of this error.
          - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new
              at J.parse (file:///C:/Users/tomaz/Projekti/GitHub/solidstart/sol/node_modules/.pnpm/seroval@1.0.4/node_modules/seroval/dist/esm/production/index.mjs:17:31830)
              ... 19 lines matching cause stack trace ...
              at J.parse (file:///C:/Users/tomaz/Projekti/GitHub/solidstart/sol/node_modules/.pnpm/seroval@1.0.4/node_modules/seroval/dist/esm/production/index.mjs:17:31657)
              at J.parseWithError (file:///C:/Users/tomaz/Projekti/GitHub/solidstart/sol/node_modules/.pnpm/seroval@1.0.4/node_modules/seroval/dist/esm/production/index.mjs:17:35903)
              at file:///C:/Users/tomaz/Projekti/GitHub/solidstart/sol/node_modules/.pnpm/seroval@1.0.4/node_modules/seroval/dist/esm/production/index.mjs:17:35069 {        
            cause: [j]
          }
        }
      }
    }
  }
}
```
- error is to long for console

**Comment by sysmat** [comment]
- git repo: https://github.com/sysmat/stackblitz-solid-start-04.9

**Comment by lxsmnsyc** [comment]
I cannot replicate the exact error you had but the only error I got was `/api/reservations` is a 404 response

**Comment by sysmat** [comment]
@lxsmnsyc thx, `"use client";`
