### ISSUE TITLE
[Bug?]: Example for server actions appears to be broken

### ISSUE THREAD

**Issue by petevdp** [solidjs/solid-start#1298]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```tsx
const isAdmin = action(async (formData: FormData) => {
    'use server'
    await new Promise((resolve, reject) => setTimeout(resolve, 1000))
    const username = formData.get('username')
    if (username === 'admin') throw redirect('/admin')
    return new Error('Invalid username')
})

function MyComponent() {
    return (
        <form action={isAdmin} method="post">
            <label for="username">Username:</label>
            <input type="text" name="username" />
            <input type="submit" value="submit" />
        </form>
    )
}
```

The code above taken from [here](https://start.solidjs.com/core-concepts/actions#server-actions) returns the following error:

```
[h3] [unhandled] NotSupportedError: multipart/form-data not supported
    at Request.formData (node:internal/deps/undici/undici:2383:19)
    ... 2 lines matching cause stack trace ...
    at async Server.toNodeHandle (file:///home/pete/projects/petevdp-xyz/node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1885:7) {
  cause: NotSupportedError: multipart/form-data not supported
      at Request.formData (node:internal/deps/undici/undici:2383:19)
      at handleServerFunction (/home/pete/projects/petevdp-xyz/node_modules/.pnpm/@solidjs+start@0.4.10_solid-js@1.8.12_vinxi@0.1.4_vite@5.0.12/node_modules/@solidjs/start/config/server-handler.js:70:31)
      at async Object.handler (file:///home/pete/projects/petevdp-xyz/node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1675:19)
      at async Server.toNodeHandle (file:///home/pete/projects/petevdp-xyz/node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1885:7) {
    code: 'UND_ERR_NOT_SUPPORTED'
  },
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```

See below for full reproduction

### Expected behavior 🤔

It should correctly parse the form data

### Steps to reproduce 🕹

Steps:

[link to repro](https://github.com/petevdp/solidstart-server-actions-repro)
1. `git clone git@github.com:petevdp/solidstart-server-actions-repro`
2. `pnpm i && pnpm run dev`
3. fill out username field and submit 
4. check error in dev server output

the repository above was produced with `pnpm create solid` and the "basic" template

### Your environment 🌎

```shell
System:
  OS:  EndeavourOS Linux x86_64 (arch)
Binaries
  node: v18.10.0
  pnpm: 8.14.0

repro: https://github.com/petevdp/solidstart-server-actions-repro
```

**Comment by petevdp** [comment]
So I just tried with node v21.6.1 and it works there, so I'm going to chalk this up to using an old node version. Will close for now
