### ISSUE TITLE
[Bug?]: Server functions don't work if invoked without an argument

### ISSUE THREAD

**Issue by pureliani** [solidjs/solid-start#1328]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I wanted to test out server functions by setting up a minimal example, where clicking the button logs "Hello" on server, but when i clicked the button i got error on the server. here is the setup:
```tsx
// routes/index.tsx

const hello = async () => {
  "use server";
  console.log('Hello')
}

export default function Home() {
  return (
    <button
      class="px-8 py-2 rounded-full bg-rose-600 text-white"
      onClick={() => {
        hello()
      }}>
      Hello
    </button>
  );
}
```
and here is the error:
```bash
[h3] [unhandled] TypeError: Cannot read properties of null (reading 'startsWith')
    at handleServerFunction (/home/furel/Desktop/testapp/node_modules/@solidjs/start/config/server-handler.ts:74:21)
    ... 2 lines matching cause stack trace ...
    at async Server.toNodeHandle (file:///home/furel/Desktop/testapp/node_modules/h3/dist/index.mjs:1907:7) {
  cause: TypeError: Cannot read properties of null (reading 'startsWith')
      at handleServerFunction (/home/furel/Desktop/testapp/node_modules/@solidjs/start/config/server-handler.ts:74:21)
      at async file:///home/furel/Desktop/testapp/node_modules/h3/dist/index.mjs:1697:19
      at async Object.callAsync (/home/furel/Desktop/testapp/node_modules/unctx/dist/index.cjs:74:16)
      at async Server.toNodeHandle (file:///home/furel/Desktop/testapp/node_modules/h3/dist/index.mjs:1907:7),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```
Seems that calling the `hello()` function with any argument: undefined, null, 1, "", {}, etc.. fixes the issue, e.g:

```tsx
const hello = async () => {
  "use server";
  console.log('hello')
}

export default function Home() {
  return (
    <button
      class="px-8 py-2 rounded-full bg-rose-600 text-white"
      onClick={() => {
        hello(1) // <--- this fixes the issue for some reason, typescript isn't happy though
      }}>
      Hello
    </button>
  );
}

```

### Expected behavior 🤔

Should log the "Hello" string in the server terminal

### Steps to reproduce 🕹

Steps:

1. Create a server function via `"use server";` that doesn't take any arguments
2. Call it without any arguments

### Your environment 🌎

```shell
System:
  OS: Pop!_OS 22.04 LTS
  CPU: (8) arm64
Binaries:
  Bun: 1.0.11
npmPackages:
  @solidjs/router: ^0.12.0
  @solidjs/start: ^0.5.5
  vinxi: ^0.2.1
```

**Comment by pureliani** [comment]
Issue has been resolved by: https://github.com/solidjs/solid-start/pull/1329
