### ISSUE TITLE
solidstart with auth -> failure:  Missing "./data" export in "solid-start" package

### ISSUE THREAD

**Issue by DBBrowne** [solidjs/solid-start#151]
```
<project-folder> $ npm init solid@next         

create-solid version 0.1.0-alpha.75

Welcome to the SolidStart setup wizard!

There are definitely bugs and some feature might not work yet.
If you encounter an issue, have a look at https://github.com/solidjs/solid-start/issues and open a new one, if it is not already tracked.

✔ Which template do you want to use? › with-auth
✔ Server Side Rendering? … no
✔ Use TypeScript? … no

found matching commit hash: cee57b7708d6c90b2e8336d4116c891b21f95046

...

<project-folder> $ npm install
...
<project-folder> $ npm run dev


```

>>>

```
22:52:00 [vite] Internal server error: Missing "./data" export in "solid-start" package
  Plugin: vite:import-analysis
  File: <project-path>/src/routes/login.jsx
```
![image](https://user-images.githubusercontent.com/72463218/175791607-e6799edd-f111-410f-a655-e5a7d23872fc.png)

**Comment by nksaraf** [comment]
Heyy this was an issue in the examples are they are served from `main` branch here, but we changed some APIs without doing a release yet that caused this mismatch. We are going to do a release soon and that should fix this!

**Comment by dertieran** [comment]
I'm also having issues running the ssr version of the `with-auth` template.
Not sure if this is related but at least the final error is different.

```
✔ Which template do you want to use? › with-auth
✔ Server Side Rendering? … yes
✔ Use TypeScript? … yes
found matching commit hash: 25406e4ff746066b11123fb511b0d41ba2b0e12b
```

<details>
<summary>Error Log</summary>

```
GET /
Missing "./data" export in "solid-start" package
Missing "./data" export in "solid-start" package (x2)
11:16:36 AM [vite] Error when evaluating SSR module /node_modules/cookie/index.js?v=2a8788d2:
ReferenceError: exports is not defined
    at /node_modules/cookie/index.js?v=2a8788d2:15:1
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:15)
11:16:36 AM [vite] Error when evaluating SSR module /node_modules/solid-start/session/cookies.ts:
ReferenceError: exports is not defined
    at /node_modules/cookie/index.js?v=2a8788d2:13:1
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:15)
11:16:36 AM [vite] Error when evaluating SSR module /node_modules/solid-start/session/cookieStorage.ts:
ReferenceError: exports is not defined
    at /node_modules/cookie/index.js?v=2a8788d2:11:1
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:15)
11:16:36 AM [vite] Error when evaluating SSR module /node_modules/solid-start/session/index.ts?v=2a8788d2:
ReferenceError: exports is not defined
    at /node_modules/cookie/index.js?v=2a8788d2:9:0
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:15)
11:16:36 AM [vite] Error when evaluating SSR module /src/db/session.tsx:
ReferenceError: exports is not defined
    at /node_modules/cookie/index.js?v=2a8788d2:7:0
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:15)
11:16:36 AM [vite] Error when evaluating SSR module /src/routes/index.tsx?data:
ReferenceError: exports is not defined
    at /node_modules/cookie/index.js?v=2a8788d2:5:0
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:15)
11:16:36 AM [vite] Error when evaluating SSR module /node_modules/solid-start/root/Routes.tsx:
ReferenceError: exports is not defined
    at /node_modules/cookie/index.js?v=2a8788d2:3:0
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:15)
11:16:36 AM [vite] Error when evaluating SSR module /node_modules/solid-start/root/index.tsx:
ReferenceError: exports is not defined
    at /node_modules/cookie/index.js?v=2a8788d2:1:0
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50311:15)
11:16:36 AM [vite] Error when evaluating SSR module /node_modules/solid-start/entry-server/StartServer.tsx:
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:16780:19)
    at node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50162:25
    at String.replace (<anonymous>)
    at node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50152:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50151:10)
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50316:32)
11:16:36 AM [vite] Error when evaluating SSR module /node_modules/solid-start/entry-server/index.ts?v=2a8788d2:
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:16780:19)
    at node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50162:25
    at String.replace (<anonymous>)
    at node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50152:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50151:10)
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50316:32)
11:16:36 AM [vite] Error when evaluating SSR module src/entry-server:
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:16780:19)
    at node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50162:25
    at String.replace (<anonymous>)
    at node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50152:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50151:10)
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50316:32)
ERROR Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:16780:19)
    at node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50162:25
    at String.replace (<anonymous>)
    at node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50152:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50151:10)
    at instantiateModule (node_modules/vite/dist/node/chunks/dep-c9998dc6.js:50316:32)
```
</details>

**Comment by nksaraf** [comment]
> FIY I just created my own [createCookie](https://github.com/solidjs/solid-start/blob/25406e4ff746066b11123fb511b0d41ba2b0e12b/packages/start/session/index.ts#L12) implementation using [@tinyhttp/cookie](https://github.com/tinyhttp/tinyhttp/tree/master/packages/cookie?rgh-link-date=2022-07-20T09%3A24%3A05Z) and it also works fine.
> (If you don't want to maintain your own cookie implementation)

We might use this, don't want to maintain our own implementation, but esm was becoming a problem.

Also with installing latest `solid-start` version, this `./data` export issue should go away..
