### ISSUE TITLE
[Bug?]:  TypeError: Response body object should not be disturbed or locked

### ISSUE THREAD

**Issue by artecoop** [solidjs/solid-start#1578]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hey!
I'm experimenting with the new Solid Start 1.0 and hit a problem while trying to upload a simple file. For example

```ts
import { action } from '@solidjs/router';

const uploadFile = action(async (data) => {
	'use server';
	console.log(data);
});

export default function () {
	return (
		<form method="post" action={uploadFile} enctype="multipart/form-data">
			<input type="file" name="file_upload" />
			<button type="submit">Upload</button>
		</form>
	);
}
```

Give me the error

```
[h3] [unhandled] TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:4151:17)
    ... 5 lines matching cause stack trace ...
    at async Server.toNodeHandle (file:///Users/dev/solo/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:2249:7) {
  cause: TypeError: Response body object should not be disturbed or locked
      at extractBody (node:internal/deps/undici/undici:4151:17)
      at new Request (node:internal/deps/undici/undici:5084:48)
      at handleServerFunction (/Users/dev/solo/node_modules/.pnpm/@solidjs+start@1.0.3_rollup@4.18.1_solid-js@1.8.18_vinxi@0.3.14_@libsql+client@0.7.0_@types+n_fqrivpjm2ut6pdcgwnam6j2nza/node_modules/@solidjs/start/dist/runtime/server-handler.js:85:64)
      at async _callHandler (file:///Users/dev/solo/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:1821:16)
      at async file:///Users/dev/solo/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:1962:19
      at async Object.callAsync (file:///Users/dev/solo/node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)
      at async Server.toNodeHandle (file:///Users/dev/solo/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:2249:7),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

```shell
macos 14.5 on mac mini M1
node 20.15.1
pnpm 9.5.0
@solidjs/meta: "^0.29.4"
@solidjs/router: "^0.14.1"
@solidjs/start: "^1.0.3"
solid-js: "^1.8.18"
vinxi: "^0.3.14"
```

**Comment by ryansolid** [comment]
Fixed in 1.0.4
