### ISSUE TITLE
[Bug?]: Changing outDir results in error

### ISSUE THREAD

**Issue by sekoyo** [solidjs/solid-start#1590]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Running `build` command results in:

```
$ vinxi build
vinxi v0.4.1


⚙  Building your app...


📦 Compiling ssr router...
vinxi building router ssr in http mode
vite v5.3.5 building SSR bundle for production...
✓ 49 modules transformed.
something/.vite/manifest.json                 1.72 kB
something/assets/index-7whypOeP.css           0.31 kB
something/assets/ssr-CSUIEcYF.css             0.38 kB
something/assets/HttpStatusCode-DH8IeaZe.js   0.28 kB
something/about.js                            0.29 kB
something/_...404_.js                         0.52 kB
something/index.js                            0.62 kB
something/assets/index-BhCdQPVl.js            2.74 kB
something/ssr.js                             25.10 kB
✓ built in 387ms
✔ build done                                                                                                                                                                       19:50:14


📦 Compiling client router...
vinxi building router client in client mode
vite v5.3.5 building for production...
virtual:$vinxi/handler/client (1:100): "default" is not exported by "src/entry-client.tsx", imported by "virtual:$vinxi/handler/client".
✓ 56 modules transformed.
something/server-functions-manifest.json      0.03 kB │ gzip: 0.04 kB
something/.vite/manifest.json                 1.64 kB │ gzip: 0.40 kB
something/assets/index-7whypOeP.css           0.31 kB │ gzip: 0.22 kB
something/assets/client-CSUIEcYF.css          0.38 kB │ gzip: 0.27 kB
something/assets/HttpStatusCode-DjTx85av.js   0.03 kB │ gzip: 0.05 kB
something/assets/about-BU9Zyyq9.js            0.27 kB │ gzip: 0.22 kB
something/assets/_...404_-DRpAHfHL.js         0.52 kB │ gzip: 0.36 kB
something/assets/index-rwcoGSeM.js            0.74 kB │ gzip: 0.45 kB
something/assets/client-C-SCNUbM.js          21.83 kB │ gzip: 8.76 kB
something/assets/index-Dlvg7cCr.js           24.10 kB │ gzip: 9.34 kB
✓ built in 367ms
✔ build done                                                                                                                                                                       19:50:15


📦 Compiling server-fns router...
vinxi building router server-fns in http mode

 ERROR  ENOENT: no such file or directory, open '<redacted>/test-solid/.vinxi/build/client/_build/server-functions-manifest.json'                                     19:50:15

  at readFileSync (node:fs:453:20)
  at config (node_modules/@vinxi/server-functions/server.js:49:5)
  at runConfigHook (node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:66394:25)
  at async resolveConfig (node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:65845:12)
  at async Module.build (node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:64914:18)
  at async createViteBuild (node_modules/vinxi/lib/build.js:321:17)
  at async createRouterBuild (node_modules/vinxi/lib/build.js:438:2)
  at async node_modules/vinxi/lib/build.js:59:5
  at async createBuild (node_modules/vinxi/lib/build.js:58:4)
  at async Object.run (node_modules/vinxi/bin/cli.mjs:227:5)
  at async runCommand (node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (node_modules/citty/dist/index.mjs:307:11)
  at async runMain (node_modules/citty/dist/index.mjs:445:7)



 ERROR  ENOENT: no such file or directory, open '<redacted>/test-solid/.vinxi/build/client/_build/server-functions-manifest.json'                                     19:50:15

error: script "build" exited with code 1
```

### Expected behavior 🤔

Should be able to change the `outDir` of built artifacts

### Steps to reproduce 🕹

Steps:

1. bun create solid test-solid
2. Chose bare/basic
3. Try to change out dir:

```ts
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  vite: {
    build: {
      outDir: "./something",
    },
  },
});
```

### Your environment 🌎

```shell
"dependencies": {
    "@solidjs/meta": "^0.29.4",
    "@solidjs/router": "^0.14.1",
    "@solidjs/start": "^1.0.6",
    "solid-js": "^1.8.19",
    "vinxi": "^0.4.1"
  },
```
```

**Comment by dominictobias** [comment]
I think SolidStart is too buggy to use atm. Today I loaded the same codebase on my other mac and get a 500 trying to load in the browser:

```
11:49:48 AM [vite] Error when evaluating SSR module /node_modules/@solidjs/start/dist/server/index.jsx: failed to import "#start/app"
|- Error: Cannot find module '#start/app' imported from '<redacted>/node_modules/@solidjs/start/dist/server/StartServer.jsx'
    at nodeImport (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52726:19)
    at ssrImport (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52591:22)
    at eval (<redacted>/node_modules/@solidjs/start/dist/server/StartServer.jsx:8:37)
    at async instantiateModule (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52650:5)

11:49:48 AM [vite] Error when evaluating SSR module /src/entry-server.tsx: failed to import "#start/app"
|- Error: Cannot find module '#start/app' imported from '<redacted>/node_modules/@solidjs/start/dist/server/StartServer.jsx'
    at nodeImport (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52726:19)
    at ssrImport (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52591:22)
    at eval (<redacted>/node_modules/@solidjs/start/dist/server/StartServer.jsx:8:37)
    at async instantiateModule (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52650:5)

11:49:48 AM [vite] Error when evaluating SSR module $vinxi/handler/ssr: failed to import "#start/app"
|- Error: Cannot find module '#start/app' imported from '<redacted>/node_modules/@solidjs/start/dist/server/StartServer.jsx'
    at nodeImport (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52726:19)
    at ssrImport (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52591:22)
    at eval (<redacted>/node_modules/@solidjs/start/dist/server/StartServer.jsx:8:37)
    at async instantiateModule (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52650:5)

[h3] [unhandled] H3Error: Cannot find module '#start/app' imported from '<redacted>/node_modules/@solidjs/start/dist/server/StartServer.jsx'
    at nodeImport (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52726:19)
    ... 2 lines matching cause stack trace ...
    at async instantiateModule (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52650:5) {
  cause: Error: Cannot find module '#start/app' imported from '<redacted>/node_modules/@solidjs/start/dist/server/StartServer.jsx'
      at nodeImport (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52726:19)
      at ssrImport (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52591:22)
      at eval (<redacted>/node_modules/@solidjs/start/dist/server/StartServer.jsx:8:37)
      at async instantiateModule (file://<redacted>/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:52650:5) {
    code: 'ERR_MODULE_NOT_FOUND'
  },
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```

Will stick to Solid + plain Vite for now

**Comment by AlexErrant** [comment]
Related Discord convo https://discord.com/channels/722131463138705510/1252013192654098463/1252013192654098463

**Comment by brenelz** [comment]
fixed by the v2 architecture — the vinxi build chain that crashed is gone. Custom output locations are now a nitro concern: use nitro({ output: { dir: "..." } }) rather than vite.build.outDir (which nitro ignores).
