### ISSUE TITLE
[Bug?]: Firebase SSR is not working

### ISSUE THREAD

**Issue by rcannood** [solidjs/solid-start#1656]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm not sure whether this issue should be posted here or in the vinxi. I will start my posting it here, but if the issue is related to vinxi, I will repost there.

When deploying an SSR SolidStart project to Firebase, the server does not seem to be working as expected.

I created a small project to help me troubleshoot the issue: [rcannood/solid-project](https://github.com/rcannood/solid-project).

Locally (`pnpm run dev`), the application looks like this:

![Screenshot from 2024-10-22 10-32-13](https://github.com/user-attachments/assets/5a101414-ae54-4245-9126-e5f46ddf70bb)

When I visit the application hosted on Firebase, I get the following:

![Screenshot from 2024-10-22 10-33-22](https://github.com/user-attachments/assets/93a3dfc0-93aa-4117-ae76-facf96b8d4fc)

For good measure, I also deployed the application to Vercel, where everything does work:

![Screenshot from 2024-10-22 10-34-34](https://github.com/user-attachments/assets/dd972e04-5eae-4e51-b28b-1c821756c6e5)

### Expected behavior 🤔

I'm expecting the Firebase-deployed application to also say "Hello from the server!".

### Steps to reproduce 🕹

I created a minimum reproducible example:

1. https://github.com/rcannood/solid-project/commit/33460f02147eea9fa72470da750680a1962d11fd: I set up a SolidStart project
2. [8f7c55f98dbab12a3e6726c2d1c9391793f1eec8](https://github.com/rcannood/solid-project/commit/8f7c55f98dbab12a3e6726c2d1c9391793f1eec8): I enabled SSR in the `app.config.ts` and set up my Firebase project
3. https://github.com/rcannood/solid-project/commit/dc6341a4b16abe73da126138234a89a3ca6a6dde: I added a component which fetches data from the server via `createResource` and `"use server"`
4. I deployed the application to Firebase with `PRESET=firebase vinxi build` and `npx firebase-tools deploy`

**Comment by ryansolid** [comment]
I've never tried Firebase before hosting before. I understand it the basic example works but it fails as soon as you try to use server functions?

Is there anyway of getting the error logs from the server? I can see when I can get a chance to sign up and take a look at it but error might guide us to the nature of the problem.

**Comment by rcannood** [comment]
> I understand it the basic example works but it fails as soon as you try to use server functions?

Indeed!

> Is there anyway of getting the error logs from the server?

Looking through the logs, I see:

    [nitro] [request error] [unhandled] "[object Object]" is not valid JSON
      at JSON.parse (<anonymous>)  
      at parseJSONFromBytes (node:internal/deps/undici/undici:5489:19)  
      at successSteps (node:internal/deps/undici/undici:5470:27)  
      at fullyReadBody (node:internal/deps/undici/undici:4381:9)  
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
      at async consumeBody (node:internal/deps/undici/undici:5479:7)  
      at async Object.Kr [as handler] (./chunks/runtime.mjs:5836:45257)  
      at async ./chunks/runtime.mjs:3076:19  
      at async Object.callAsync (./chunks/runtime.mjs:5453:16)  
      at async toNodeHandle (./chunks/runtime.mjs:3347:7)

Happy to give you access to the Google Project and GitHub repository, if that helps :)

**Comment by rcannood** [comment]
Maybe just a quick question -- based on the information above, would you be able to make out whether this issue should be posted here in a different repository?

Thanks @ryansolid !

**Comment by brenelz** [comment]
Can you try nitro v3?

**Comment by rcannood** [comment]
Sorry, since Firebase wasn't working, I ended up switching to a different provider.

While I can't confirm nor deny that this problem has been solved by switching to nitro v3, shall we close this issue? Or do we leave it open for somebody or something else to try to reproduce this with solidstart v2 and nitro v3?

**Comment by brenelz** [comment]
We can probably close and someone can reopen if its still an issue. Thanks for rseponding.
