### ISSUE TITLE
[Bug]: Actions with latest `netlify` preset return 500 due to `Response body object should not be disturbed or locked`

### ISSUE THREAD

**Issue by serhalp** [solidjs/solid-start#1673]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The page renders "⚠️ Oops, something went wrong".

This is because the Action's `POST /_server` returns a 500.

This error is logged on the server:

```
[nitro] [request error] [unhandled] Response body object should not be disturbed or locked
```

### Expected behavior 🤔

The page [should render "✅ Correct!"](https://github.com/serhalp/repro-solidstart-nitro-response-body-disturbed/blob/d5e2c1f59a5c096e751ccef698222cd017374e21/src/routes/index.tsx#L34) because [the Action returns `true`](https://github.com/serhalp/repro-solidstart-nitro-response-body-disturbed/blob/d5e2c1f59a5c096e751ccef698222cd017374e21/src/lib/api.ts#L9)

This works as expected with:
- `vinxi dev` (doesn't exercise the `netlify` preset)
- `ntl dev` (doesn't exercise the `netlify` preset)
- using the `netlify-edge` preset instead of `netlify`
- removing [this config](https://github.com/serhalp/repro-solidstart-nitro-response-body-disturbed/blob/d5e2c1f59a5c096e751ccef698222cd017374e21/app.config.ts#L5-L8) or otherwise reverting to the `netlify-legacy` preset

### Steps to reproduce 🕹

Steps:

with https://github.com/serhalp/repro-solidstart-nitro-response-body-disturbed (`pnpm i`) and netlify-cli (`npm i -g netlify-cli`)

1. `ntl serve`
2. click "click me"

or

1. create a Netlify site and link it (e.g. `ntl init`)
2. `ntl deploy --build`
3. click "click me"

I've also deployed it here: https://672c1abc039334ad67383d7e--repro-solidstart-response-disturbed.netlify.app/.

### Context 🔦

Seems to be similar to https://github.com/solidjs/solid-start/pull/1577...?

If I add some logging [here](https://github.com/nitrojs/nitro/blob/4307202f5aa5099e53b1653f382df393e929e086/src/runtime/internal/error.ts#L23) (necessary because the error handling in that function strips the stack trace and all details outside of dev but this bug can only be reproduced in "real" environments) I can see that this is throwing [from here](https://github.com/solidjs/solid-start/blob/3da66e456cab1b401e6aeb0b06491f5dbd418527/packages/start/src/runtime/server-handler.ts#L154).

### Your environment 🌎

macOS Monterey 12.7.1 (21G920)
Firefox 131.0.3

```
$ uname -a
Darwin [...] 21.6.0 Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023;
$ node -v
v22.9.0
$ pnpm -v
9.6.0
```

**Comment by serhalp** [comment]
@pi0 I see that in many other presets we're reading in the whole body stream and then passing it back to Nitro as a Buffer:
- [Cloudflare Workers](https://github.com/nitrojs/nitro/blob/4307202f5aa5099e53b1653f382df393e929e086/src/presets/cloudflare/runtime/cloudflare-worker.ts#L44-L47)
- [Vercel Edge](https://github.com/nitrojs/nitro/blob/4307202f5aa5099e53b1653f382df393e929e086/src/presets/vercel/runtime/vercel-edge.ts#L10-L12)

I suspect this is related. In both cases I can see [this being added](https://github.com/nitrojs/nitro/commit/561bb5a16f4d8bf59ff08b446ec4d5d392f4e867) specifically to fix something unspecified.

Do we need to do something like this the new `netlify` preset? If so, I'm happy to open a PR but can you point me to the underlying issue or reason? and I wonder if there's some day we can fix this at the source (is that what https://github.com/nitrojs/nitro/issues/1721#issuecomment-2425419583 is trying to do?) or at least make it harder to regress.

**Comment by serhalp** [comment]
Whew, finally found the time to try to create a Nitro repro of this, but it seems to work just fine:

- repo: https://github.com/serhalp/repro-nitro-response-body-disturbed
- deployment with new `netlify` preset: https://repro-nitro-response-body-disturbed.netlify.app/
- works fine: `curl -X POST --data "hello world" https://repro-nitro-response-body-disturbed.netlify.app/`
- works fine: `curl -H "Content-Type: application/json" -X POST --data '{"msg": "hello world"}' https://repro-nitro-response-body-disturbed.netlify.app/`

So it seems to be specific to SolidStart. Any ideas @ryansolid? or ideas for workarounds?

I could maybe look into fixing myself if either of you could give me a little guidance here as there's, uhh, [quite a lot going on here](https://github.com/solidjs/solid-start/blob/71236986c21527267ce36221c964cd2c5fca705f/packages/start/src/runtime/server-handler.ts#L120-L171) I'm a bit wary of diving in without understanding the stories behind all these workarounds. Thanks!

**Comment by ryansolid** [comment]
I admit I have no idea. All the hacks in there were for getting around previous issues we had in various envs and I wasn't involved in implementing any of them. I verified them on various platforms but for the most part it was due to gaps in adapters for those envs. It's possible some of them are no longer needed. If you look one of the comments sounds almost like it was to fix an issue similar to what you are facing by cloning the request rather than using a locked one. It is interesting that no longer works?...

**Comment by serhalp** [comment]
@ryansolid @pi0 Hey friends! I finally found some time to poke around and found this fix that works: https://github.com/solidjs/solid-start/pull/1705. What do you think? (One again, I have no idea what I'm doing in here!)

**Comment by serhalp** [comment]
Fixed by #1705. Thanks! 🚀

**Comment by serhalp** [comment]
😅 Damn, this regressed again in vinxi@0.5.4 (nitro 2.10.4 → 2.11.4). I only happened to notice in the Renovate PR for this silly app I made a while back: https://github.com/serhalp/artifice/pull/42.

I'll try to find time to open a proper issue with a new minimal repro, but I just wanted to signal this in the meantime. Seems like this is on the nitro side this time @pi0 since it's introduced by a vinxi bump?

**Comment by serhalp** [comment]
oh, quick stack trace at least:

```
Apr 13, 09:13:46 AM: 10ea763c ERROR  [request error] [unhandled] [POST] https://deploy-preview-42--artificegame.netlify.app/_server
 TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:5351:17)
    ... 8 lines matching cause stack trace ...
    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26) {
  cause: TypeError: Response body object should not be disturbed or locked
      at extractBody (node:internal/deps/undici/undici:5351:17)
      at new Request (node:internal/deps/undici/undici:6332:48)
      at Object.es [as handler] (file:///var/task/chunks/nitro/nitro.mjs:6975:27)
      at async file:///var/task/chunks/nitro/nitro.mjs:1880:19
      at async Object.callAsync (file:///var/task/chunks/nitro/nitro.mjs:4521:16)
      at async toNodeHandle (file:///var/task/chunks/nitro/nitro.mjs:2151:7)
      at async b$2 (file:///var/task/chunks/nitro/nitro.mjs:846:7015)
      at async Module.handler (file:///var/task/chunks/nitro/nitro.mjs:8262:13)
      at async Runtime.handler (file:///var/task/___netlify-bootstrap.mjs:2:33741)
      at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```
