### ISSUE TITLE
[Bug?]: TRPC example fails on deno-deploy

### ISSUE THREAD

**Issue by adamstringer** [solidjs/solid-start#1698]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The TRPC example fails in production on deno deploy returning the following error within the server logs.
```
 << query  #1 example.hello  {
  input: "world",
  result: TRPCClientError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
    at Function.from (file:///src/server/index.ts:10974:16)
    at file:///src/server/index.ts:11113:36
    at eventLoopTick (ext:core/01_core.js:175:7)
Caused by SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:394:14)
    at consumeBody (ext:deno_fetch/22_body.js:260:12)
    at eventLoopTick (ext:core/01_core.js:175:7) {
    meta: {
      response: Response {
        body: ReadableStream { locked: true },
        bodyUsed: true,
        headers: Headers {
          "content-length": "98",
          "content-type": "text/plain; charset=utf-8",
          date: "Thu, 19 Dec 2024 16:22:53 GMT",
          server: "deno/gcp-europe-west2",
          via: "http/1.1 edgeproxy"
        },
        ok: false,
        redirected: false,
        status: 508,
        statusText: "Loop Detected",
        url: "https://test-stack.deno.dev/api/trpc/example.hello?batch=1&input=%7B%220%22%3A%22world%22%7D"
      }
    },
    shape: undefined,
    data: undefined,
    name: "TRPCClientError"
  },
  elapsedMs: 72
}
```

This only occurs when running TRPC calls on the server via createAsync. However when the TRPC call originates from the client it works as expected

```
export default function Home() {
  const hello = createAsync(() => api.example.hello.query("world")); // FAILS
  const [hello2] = createResource(() => api.example.hello.query("world"), {
    initialValue: "test",
  }); // FAILS

  onMount(async() => {
    const hello = await api.example.hello.query("world");
    console.log(hello); // WORKS
  });


  return (
    <main>
      <Title>Hello World</Title>
      <h1>Hello world!</h1>
      <Counter />
      <p>
        Visit{" "}
        <a href="https://start.solidjs.com" target="_blank">
          start.solidjs.com
        </a>{" "}
        to learn how to build SolidStart apps.
      </p>
      <pre>
        <code>{JSON.stringify(hello(), null, 2)}</code>
      </pre>
    </main>
  );
}

```

### Expected behavior 🤔

TRPC calls should work with createAsync / SSR

### Steps to reproduce 🕹

Steps:

1. install TRPCexample with` deno run -A npm:create-solid`
2. change the server preset to "deno-deploy" within app.config.ts
3. deploy on deno and go to the url

### Context 🔦

Everything works great in dev when using solid-start and deno, just running into issues regarding deployment. 

### Your environment 🌎

```shell
deno 2.1.4 & Deno Deploy
```

**Comment by adamstringer** [comment]
The issue is upstream and intended. Error 508 is due to recursive requests to the same end point / deployment. 

https://github.com/denoland/deploy_feedback/issues/365#issuecomment-1510596902
