### ISSUE TITLE
Error when use `with-tailwindcss` starter template

### ISSUE THREAD

**Issue by uporot1k** [solidjs/solid-start#228]
Hi!
I just use  `with-tailwindcss` starter template and get error on page

Reproduction:
- `npm init solid@next`
- chose `with-tailwindcss` starter template
- `npm i`
- `npm run dev`

Error:
```
 root.tsx:8 Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')
    at root.tsx:8:3
    at Root (root.tsx:8:3)
    at dev.js:537:12
    at untrack (dev.js:443:12)
    at Object.fn (dev.js:533:37)
    at runComputation (dev.js:713:22)
    at updateComputation (dev.js:698:3)
    at devComponent (dev.js:544:3)
    at createComponent (dev.js:1239:17)
    at get children [as children] (StartClient.tsx:63:5)
```

**Comment by nksaraf** [comment]
Should be fixed in new template.. I'm assuming you selected non-ssr mode. Our SPA mode had not been propagated to the examples properly. Could you try this again now.. have updated the templates.
