### ISSUE TITLE
Tailwind CSS example doesn't serve content.

### ISSUE THREAD

**Issue by cohenerickson** [solidjs/solid-start#280]
```
(node:26369) UnhandledPromiseRejectionWarning: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/workspaces/-----/node_modules/stream/web' imported from /workspaces/-----/node_modules/.pnpm/solid-start@0.1.0-alpha.100_nonwz67wm5lb5x5bdfuthnoihq/node_modules/solid-start/node/globals.js
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26369) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nksaraf** [comment]
You need to be on node v16 atleast, could you try upgrading?

**Comment by aarongreenlee** [comment]
I think this issue can be closed. I had no trouble with the tailwind example this morning.
