### ISSUE TITLE
data-loading example issue

### ISSUE THREAD

**Issue by reggi** [solidjs/solid-start#365]
this example code is not working

https://start.solidjs.com/core-concepts/data-loading

1. Accessor is not used
2. Page should be export default
3. even when fixed still doesn't work locally

```
import { For, Accessor, createResource } from "solid-js";
import { useRouteData, createRouteData } from "solid-start";
 
type Student = { name: string; house: string; }
 
export function routeData() {
  return createRouteData(async () => {
    const response = await fetch("https://hogwarts.deno.dev/students");
    return await response.json() as Student[];
  });
}
 
export function Page() {
  const students = useRouteData<typeof routeData>();
 
  return (
    <ul>
      <For each={students()}>
        {(student) => <li>{student.name}</li>}
      </For>
    </ul>
  );
}
 
```

````
ErrorBoundary.tsx:27 Error: Unrecoverable Hydration Mismatch. No template for key: 0-0-0-0-0-0-0-0-0-1-0-0-0-0-1-1-0-0-1-0-0
    at getNextElement (dev.js:250:26)
    at Object.fn (dev.js:583:43)
    at runComputation (dev.js:693:22)
    at updateComputation (dev.js:676:3)
    at createMemo (dev.js:238:10)
    at Dynamic (dev.js:573:10)
    at dev.js:515:12
    at untrack (dev.js:421:12)
    at Object.fn (dev.js:511:37)
    at runComputation (dev.js:693:22)
```

**Comment by nksaraf** [comment]
Default export is the only issue.

```ts
import { For } from "solid-js";
import { createRouteData, useRouteData } from "solid-start";

type Student = { name: string; house: string };

export function routeData() {
  return createRouteData(async () => {
    const response = await fetch("https://hogwarts.deno.dev/students");
    return (await response.json()) as Student[];
  });
}

export default function Page() {
  const students = useRouteData<typeof routeData>();

  return (
    <ul>
      <For each={students()}>{student => <li>{student.name}</li>}</For>
    </ul>
  );
}
```

works for me
