### ISSUE TITLE
`npm init solid` with bare and hackernews templates results in broken apps

### ISSUE THREAD

**Issue by IgorMinar** [solidjs/solid-start#380]
```
mkdir solid-bare
cd solid-bare
npm init solid
# bare or hackernews | SSR | ts or no ts
npm install
npm run dev -- --open
```

results in broken app:

![Screen Shot 2022-10-28 at 3 52 47 PM](https://user-images.githubusercontent.com/216296/198747971-08135ddb-f8ce-41ae-a122-8d0c0d9be98c.png)

The console output is:

```
dev.js:249 Unable to find DOM nodes for hydration key: 0-0-0-0-0-0-0-0-0-1-0-0-0-0-2-1-0-0-1-0-0
getNextElement @ dev.js:249
ErrorBoundary.tsx:27 TypeError: Cannot read properties of null (reading 'nextSibling')
    at index.jsx:4:3
    at Home (index.jsx:8:15)
    at @solid-refresh:10:42
    at untrack (dev.js:421:12)
    at Object.fn (@solid-refresh:10:28)
    at runComputation (dev.js:693:22)
    at updateComputation (dev.js:676:3)
    at createMemo (dev.js:238:10)
    at hmrCompWrapper (@solid-refresh:7:20)
    at dev.js:1351:17
```

Reproducible with versions:
```
├── @solidjs/meta@0.28.2
├── @solidjs/router@0.5.0
├── solid-js@1.6.0
├── solid-start-node@0.2.0
├── solid-start@0.2.0
├── undici@5.12.0
└── vite@3.2.1
```

**Comment by nksaraf** [comment]
Heyy this should be fixed now! It was a vite change that broke some of our stuff, but we dealt with this. Can you try solid-start@0.2.1 to confirm is the issue still persists.

**Comment by IgorMinar** [comment]
works now. thank you @nksaraf!
