### ISSUE TITLE
server$ should work in not only .jsx and .tsx files

### ISSUE THREAD

**Issue by jchatard** [solidjs/solid-start#408]
Using `server$` as default export breaks build.

```ts
export default server$(async (path: string) => {
  // Do stuff
});
```

Produces:

```
An error occured while server rendering /program/33740:
  
Error: Should be compiled away
    at Module.server$ [as default] (/Users/jchatard/Documents/XXXX/XXXX.fr/front-solidjs/node_modules/.pnpm/solid-start@0.2.5_hbwrjiud3j45e6mxm6q434ty3e/node_modules/solid-start/server/server-functions/server.ts:21:8)
    at /Users/jchatard/Documents/XXXX/XXXX.fr/front-solidjs/src/lib/fetcher.ts:14:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async instantiateModule (file:///Users/jchatard/Documents/XXXX/XXXX.fr/front-solidjs/node_modules/.pnpm/vite@3.2.3/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:53053:9
```

But this works:

```ts
export const fetchAPI = () => server$(async (path: string) => {
  // Do stuff
}); 
```

Works!

**Comment by jchatard** [comment]
And here's a repro: https://github.com/jchatard/should_be_compiled_away

**Comment by jchatard** [comment]
To give an update, I have been struggling to make it work in my full app, until I stumbled accross this comment from @nksaraf on [Discord](https://discord.com/channels/722131463138705510/722167424186843267/973906532804739072): 

> Yeah this is very fair... since its only me who has worked on it and used it extensively.. subconciously I know what to do.. one thing to look out for it to make sure the files are .tsx when you use server functions since that can cause the compiled error thing

So renaming files which contained `server$`calls from `*.ts` to `*.tsx`, solved my issue.
