### ISSUE TITLE
HEAD: solid-start/routes.js: ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#45]
```
ReferenceError: exports is not defined
    at processRoute (file:///home/brian/work/portfoliome/censible-core/vendor/solid-start/packages/start/routes.js:65:44)
    at file:///home/brian/work/portfoliome/censible-core/vendor/solid-start/packages/start/routes.js:82:5
    at Array.reduce (<anonymous>)
    at getRoutes (file:///home/brian/work/portfoliome/censible-core/vendor/solid-start/packages/start/routes.js:80:29)
    at async Context.load (file:///home/brian/work/portfoliome/censible-core/vendor/solid-start/packages/start/plugin.js:24:26)
    at async Object.load (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/vite@2.7.12/node_modules/vite/dist/node/chunks/dep-0351185a.js:36961:32)
    at async doTransform (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/vite@2.7.12/node_modules/vite/dist/node/chunks/dep-0351185a.js:51996:24)
```

**Comment by nksaraf** [comment]
This should be fixed by #44
