### ISSUE TITLE
Unstable Islands don't work on windows

### ISSUE THREAD

**Issue by orenelbaum** [solidjs/solid-start#498]
Unstable Islands don't work on windows, it seems to be due to a problem with the handling of path separators.
This is the error I'm getting
```
[plugin:vite:import-analysis] Failed to resolve import "/srccomponentsCounter.tsx" from "..\..\..\..\..\srccomponentsCounter.tsx?island". Does the file exist?
/srccomponentsCounter.tsx:2:34
1  |  import Component from '/srccomponentsCounter.tsx';
   |                         ^
2  |  window._$HY.island("", Component);
3  |  export default Component;
    at formatError (solid-start-test/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39975:46)
    at TransformContext.error (solid-start-test/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:39971:19)
    at normalizeUrl (solid-start-test/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36839:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransformContext.transform (solid-start-test/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36972:47)
    at async TransformContext.plugin.transform (solid-start-test/node_modules/@vinxi/vite-plugin-inspect/dist/index.mjs:2903:25)
    at async Object.transform (solid-start-test/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40228:30)
    at async loadAndTransform (solid-start-test/node_modules/
```

**Comment by orenelbaum** [comment]
fixed with https://github.com/solidjs/solid-start/pull/500
