### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rtritto** [solidjs/solid-start#511]
### Steps to reproduce
- Clone [with-tailwindcss](https://github.com/solidjs/solid-start/tree/main/examples/with-tailwindcss)
- `yarn set version canary`
- `yarn`
- `yarn dev`

### Actual
```console
 solid-start dev
 version  0.2.7
failed to load config from C:\solidjs-with-tailwindcss\vite.config.ts
C:\solidjs-with-tailwindcss\.pnp.cjs:8319
  resolve(p) {
         ^

RangeError: Maximum call stack size exceeded
    at ZipOpenFS.resolve (C:\solidjs-with-tailwindcss\.pnp.cjs:8319:10)
    at ZipOpenFS.makeCallSync (C:\solidjs-with-tailwindcss\.pnp.cjs:8968:30)
    at ZipOpenFS.readdirSync (C:\solidjs-with-tailwindcss\.pnp.cjs:8867:17)
    at VirtualFS.readdirSync (C:\solidjs-with-tailwindcss\.pnp.cjs:7843:24)
    at PosixFS.readdirSync (C:\solidjs-with-tailwindcss\.pnp.cjs:7843:24)
    at NodePathFS.readdirSync (C:\solidjs-with-tailwindcss\.pnp.cjs:7843:24)
    at find (file:///C:/solidjs-with-tailwindcss/.yarn/__virtual__/solid-start-virtual-6e76dd9961/3/Users/<user>/AppData/Local/Yarn/Berry/cache/solid-start-npm-0.2.7-cdd540628f-9.zip/node_modules/solid-start/vite/plugin.js:546:20)
    at find (file:///C:/solidjs-with-tailwindcss/.yarn/__virtual__/solid-start-virtual-6e76dd9961/3/Users/<user>/AppData/Local/Yarn/Berry/cache/solid-start-npm-0.2.7-cdd540628f-9.zip/node_modules/solid-start/vite/plugin.js:548:10)
    at find (file:///C:/solidjs-with-tailwindcss/.yarn/__virtual__/solid-start-virtual-6e76dd9961/3/Users/<user>/AppData/Local/Yarn/Berry/cache/solid-start-npm-0.2.7-cdd540628f-9.zip/node_modules/solid-start/vite/plugin.js:548:10)
    at find (file:///C:/solidjs-with-tailwindcss/.yarn/__virtual__/solid-start-virtual-6e76dd9961/3/Users/<user>/AppData/Local/Yarn/Berry/cache/solid-start-npm-0.2.7-cdd540628f-9.zip/node_modules/solid-start/vite/plugin.js:548:10)
```

### Expected
No error

### Possible reason
Search not existing `node_modules` folder with Plug'n'Play (pnp loader)
https://github.com/solidjs/solid-start/blob/e625ec61ca5610cf4bf309507a2f782e7535627a/packages/start/vite/plugin.js#L551

**Comment by danieltroger** [comment]
Also suffering from this. Would love to use yarn 3 everywhere.

**Comment by rtritto** [comment]
Fixed with https://github.com/solidjs/solid-start/commit/fc65a21e86122da186e3fd98b4cb57fe8d5c8046 in _v0.2.12_.

FYI @danieltroger
