### ISSUE TITLE
Proposal: Implement a Workaround for the Stackblitz EACCES Error

### ISSUE THREAD

**Issue by leoj3n** [solidjs/solid-start#550]
Here is a Stackblitz project created by "connecting" to this repository (`https://github.com/solidjs/solid-start`):

https://stackblitz.com/edit/node-2fuiyg?file=package.json

The terminal output upon opening the project:

```console
~/projects/node-2fuiyg
❯ pnpm install
Scope: all 24 workspace projects
 WARN  There are cyclic workspace dependencies
preResolution: Hydrating content-addressable store.
Content-addressable store is at: ~/.local/share/pnpm/store/v3
Progress: total 901, downloaded 901, done

Lockfile is up to date, resolution step is skipped
Packages: +897
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 897, reused 877, downloaded 6, added 897, done

dependencies:
+ cross-env 7.0.3

devDependencies:
+ @cloudflare/kv-asset-handler 0.2.0
+ @rollup/plugin-commonjs 22.0.2
+ @rollup/plugin-json 4.1.0
+ @rollup/plugin-node-resolve 13.3.0
+ @solidjs/meta 0.28.2
+ @solidjs/router 0.5.0
+ @tailwindcss/typography 0.5.7
+ @trpc/client 9.27.4
+ @trpc/server 9.27.4
+ coveralls 3.1.1
+ debug 4.3.4
+ fast-glob 3.2.12
+ rimraf 3.0.2
+ rollup 2.79.1
+ solid-js 1.6.2
+ solid-mdx 0.0.6
+ solid-start 0.2.7 <- packages/start
+ solid-start-cloudflare-workers 0.2.7 <- packages/start-cloudflare-workers
+ solid-start-mdx 0.2.7 <- packages/mdx
+ solid-start-netlify 0.2.7 <- packages/start-netlify
+ solid-start-node 0.2.7 <- packages/start-node
+ tailwindcss 3.2.2
+ tippy.js 6.3.7
+ turbo 1.6.3
+ typescript 4.7.4
+ undici 5.12.0
+ vite 3.2.2
+ zod 3.19.1

Done in 2m 30.4s

~/projects/node-2fuiyg 2m 31s
❯ ls -la packages/start/bin.cjs
total 1
-rw-r--r--  1  staff  staff  18110  Dec  18  15:18  packages/start/bin.cjs   
```

Terminal output of attempting to run `pnpm run docs:dev`:

```console
~/projects/node-2fuiyg
❯ pnpm run docs:dev

> solid-start-monorepo@0.1.0 docs:dev /home/projects/node-2fuiyg
> solid-start dev

Error [EACCES]: spawn solid-start EACCES
    at InternalError.get (https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:6:292488)
    at getStackString (https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:6:103714)
    at https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:6:99368
    at https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:6:101165
    at formatValue (https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:6:103551)
    at inspect (https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:6:92244)
    at _0x22e040 (https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:15:150165)
    at _0x14b72d (https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:8:131174)
    at https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:15:109580
    at process._0x30140f [as reallyExit] (https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:15:109604)
    at _0xf9df6f (https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:8:261597)
    at https://node2fuiyg-fnfd.w-credentialless.staticblitz.com/blitz.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b.js:15:515843 {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn solid-start',
  path: 'solid-start',
  spawnargs: [ 'dev' ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

Even though the `packages/start/bin.cjs` in this repo has executable permissions, those permissions for whatever reason do not translate to Stackblitz...

Locally cloned repo:

```console
$ ls -la ./packages/start/bin.cjs
-rwxr-xr-x  1 leoj  staff  18110 Dec 18 15:15 ./packages/start/bin.cjs

$ git ls-files -s ./packages/start/bin.cjs
100755 74430e04d6943ffd815535c78347b9545ec9b42b 0	packages/start/bin.cjs
```

Remotely on Stackblitz:

```console
❯ ls -la ./packages/start/bin.cjs
total 1
-rw-r--r--  1  staff  staff  18110  Dec  18  15:18  ./packages/start/bin.cjs
```

The solution is to `chmod +x ./packages/start/bin.cjs`:

```console
❯ ls -la ./packages/start/bin.cjs
total 1
-rw-r--r--  1  staff  staff  18110  Dec  18  15:18  ./packages/start/bin.cjs   

~/projects/node-2fuiyg
❯ pnpm run stackblitz-chmod-fix

> solid-start-monorepo@0.1.0 stackblitz-chmod-fix /home/projects/node-2fuiyg
> chmod +x ./packages/start/bin.cjs


~/projects/node-2fuiyg 1s
❯ ls -la ./packages/start/bin.cjs
total 1
-rwxr-xr-x  1  staff  staff  18110  Dec  18  15:18  ./packages/start/bin.cjs* 
```

Other than just adding note in the README for this repo, this could be made a `post-install` script that always runs... Perhaps the script can check for the Stackblitz domain and then chmod the file.

Is there any desire to patch this so the repo works on Stackblitz without a bunch of troubleshooting?

**Comment by ryansolid** [comment]
A note in the README seems fine. I am wary of adding a `post-install` script.

**Comment by fvsch** [comment]
FYI, StackBlitz doesn't run `postinstall` scripts.

**Comment by fvsch** [comment]
Just a heads up that at StackBlitz, it's likely that our priority will be to make this specific use case work well in Codeflow, and we might not prioritize making it work in our classic editor.

See [my comment here](https://github.com/stackblitz/core/issues/2226#issuecomment-1361269760) for details.

(Not a final company decision, this is my understanding only. We’re also on a two week company-wide Winter break, so there will likely be few or no updates on this topic until January.)
