### ISSUE TITLE
Starter templates are broken

### ISSUE THREAD

**Issue by shinebayar-g** [solidjs/solid-start#653]
Most of the starter templates seems to be broken.

This is log from `bare` version.

```sh
❯ npm run dev

> dev
> solid-start dev

 solid-start dev
 version  0.2.13
 adapter  node

  VITE v3.2.5  ready in 415 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  Inspect: http://localhost:5173/__inspect/

  ➜  Page Routes:
     ┌─ http://localhost:5173/*404
     └─ http://localhost:5173/

  ➜  API Routes:
     None! 👻

  > Server modules:
   http://localhost:5173/_m/*

GET http://localhost:5173/
[postcss] Cannot read properties of undefined (reading 'config')
[postcss] Cannot read properties of undefined (reading 'config') (x2)
An unhandled error occured: TypeError: [postcss] Cannot read properties of undefined (reading 'config')
    at getTailwindConfig (/home/ubuntu/myapp/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:84:63)
    at /home/ubuntu/myapp/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:96:92
    at /home/ubuntu/myapp/node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11
    at plugins (/home/ubuntu/myapp/node_modules/tailwindcss/lib/index.js:38:63)
    at LazyResult.runOnRoot (/home/ubuntu/myapp/starter-bare/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/ubuntu/myapp/starter-bare/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/ubuntu/myapp/starter-bare/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/home/ubuntu/myapp/starter-bare/node_modules/postcss/lib/lazy-result.js:206:17)
```

tailwind version seems to be working. I tried Hackernews, Websocket, Auth all were broken.

**Comment by shinebayar-g** [comment]
Ah I found the problem, I initialized the project in a sub directory of existing SolidJS project. This seems to be the root cause. Initializing an application in the different directory worked.
