### ISSUE TITLE
<Title> component not compatible with @solid-primitives/i18n

### ISSUE THREAD

**Issue by tomexx** [solidjs/solid-start#703]
Hello,

I'm trying to display localized content with @solid-primitives/i18n but when I try to display such content in <title> using <Title> component I've got an error code like this:

```
An unhandled error occured: TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at SeoTitle (/src/seo/SeoTitle.tsx:8:15)
    at Proxy.createComponent (/Users/tom/projects/test/node_modules/solid-js/dist/server.cjs:286:10)
    at Object.get children [as children] (/src/route-modules/Home.tsx:18:40)
    at eval (/@fs/Users/tom/projects/test/node_modules/@solidjs/meta/dist/index.jsx:179:22)
    at Array.map (<anonymous>)
    at Module.renderTags (/@fs/Users/tom/projects/test/node_modules/@solidjs/meta/dist/index.jsx:176:15)
    at eval (/@fs/Users/tom/projects/test/node_modules/solid-start/root/Meta.tsx:14:89)
    at Array.<anonymous> (/Users/tom/projects/test/node_modules/solid-js/web/dist/server.cjs:629:65)
    at injectAssets (/Users/tom/projects/test/node_modules/solid-js/web/dist/server.cjs:663:70)
    at doShell (/Users/tom/projects/test/node_modules/solid-js/web/dist/server.cjs:410:12)
    at complete (/Users/tom/projects/test/node_modules/solid-js/web/dist/server.cjs:428:9)
    at checkEnd (/Users/tom/projects/test/node_modules/solid-js/web/dist/server.cjs:312:24)
```

i18n works correctly when used with other/regular components...

Is there possibly a quick fix for this?

Thanks a lot

**Comment by atk** [comment]
Can you show us how you used it?

**Comment by tomexx** [comment]
> Can you show us how you used it?

Please check repo https://github.com/tomexx/solid-start-primitives-i18n

**Comment by tomexx** [comment]
> Can you show us how you used it?

I've added more examples/commits. Not sure if it works like this by design... If yes, please feel free to close this issue.

https://github.com/tomexx/solid-start-primitives-i18n/commits/master

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
