### ISSUE TITLE
with-vitest no SSR Cannot find module error

### ISSUE THREAD

**Issue by dtbenson43** [solidjs/solid-start#720]
OS: Microsoft Windows 11 Home
Version: 10.0.22000 Build 22000

I use `npm init solid@latest`
I select "with-vitest"
I select "n" when prompted about SSR
I select "Y" when prompted about typescript

when I run `npm run dev`

I get this error in the terminal:
```
GET http://localhost:3000/
An unhandled error occured: Error: Cannot find module 'C:UsersdbensDocumentsGitHub
ite-solid-typescript
ode_modulessolid-startdevCsrRoot.tsx' imported from 'C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/solid-start/entry-server/StartServer.tsx'
    at viteResolve (file:///C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53393:25)
    at nodeImport (file:///C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53430:15)
    at ssrImport (file:///C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53318:20)
    at eval (/node_modules/solid-start/entry-server/StartServer.tsx:16:37)
    at async instantiateModule (file:///C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53364:9)
```

and this error is displayed at localhost:3000:

```
An error occured while server rendering /:

	Cannot find module 'C:UsersdbensDocumentsGitHubite-solid-typescript
ode_modulessolid-startdevCsrRoot.tsx' imported from 'C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/solid-start/entry-server/StartServer.tsx'
Error: Cannot find module 'C:UsersdbensDocumentsGitHubite-solid-typescript
ode_modulessolid-startdevCsrRoot.tsx' imported from 'C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/solid-start/entry-server/StartServer.tsx'
    at viteResolve (file:///C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53393:25)
    at nodeImport (file:///C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53430:15)
    at ssrImport (file:///C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53318:20)
    at eval (/node_modules/solid-start/entry-server/StartServer.tsx:16:37)
    at async instantiateModule (file:///C:/Users/dbens/Documents/GitHub/vite-solid-typescript/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:53364:9
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

If I repeat the process with SSR on or I remove the `ssr: false` property from the solid options vite.config.ts the project works

Not sure what the issue could be

**Comment by atk** [comment]
It seems you're running this directly on Windows without WSL; this is currently untested. I need to setup a test VM, since I'm on Linux.

**Comment by dtbenson43** [comment]
> It seems you're running this directly on Windows without WSL; this is currently untested. I need to setup a test VM, since I'm on Linux.

yes I'm running directly on windows

**Comment by AlexErrant** [comment]
I believe this is a regression with @latest. Can you try with these versions? (I'd try myself but gotta dash for now.)

```
    "solid-js": "^1.6.9",
    "solid-start": "^0.2.15",
```

**Comment by dtbenson43** [comment]
> I believe this is a regression with @latest. Can you try with these versions? (I'd try myself but gotta dash for now.)
> 
> ```
>     "solid-js": "^1.6.9",
>     "solid-start": "^0.2.15",
> ```

I installed these versions of solid-js and solid-start and the project now runs without error using `npm run dev`

**Comment by dtbenson43** [comment]
Although the project is running now, it appears to be using SSR even though I selected no and the `ssr: false` property is in the solid options vite.config.ts

**Comment by AlexErrant** [comment]
(on my phone cause I'm mad) some ssr occurs _in dev_ for 'ssr:false'. See https://github.com/solidjs/solid-start/issues/519#issuecomment-1341687247

**Comment by dtbenson43** [comment]
> (on my phone cause I'm mad) some ssr occurs _in dev_ for 'ssr:false'. See [#519 (comment)](https://github.com/solidjs/solid-start/issues/519#issuecomment-1341687247)

ah okay that makes sense, thank you for the help

**Comment by ryansolid** [comment]
That issue of code being run on `ssr: false` should have been fixed for the most part which is where this new issue was introduced specifically on windows. I didn't expect an issue as the path handling here is identical to other locations but apparently something breaks here specifically. Looking into it best I can without a windows setup.
