### ISSUE TITLE
Parse failure: Octal literal in strict mode (8:20)

### ISSUE THREAD

**Issue by jean13360** [solidjs/solid-start#723]
Hi,

When a create a new solid project with "npm init solid@latest".
I choose blank projet with or withou typescript support .

I do npm init and after  npm run dev -- --open --port 8082

And i have this error 

Parse failure: Octal literal in strict mode (8:20)
Contents of line 8: import Root from "E:\3-TESI22\solidjs\webco\node_modules\solid-start\dev\CsrRoot.tsx";
An unhandled error occured: Error: Parse failure: Octal literal in strict mode (8:20)
Contents of line 8: import Root from "E:\3-TESI22\solidjs\webco\node_modules\solid-start\dev\CsrRoot.tsx";
    at ssrTransformScript (file:///E:/3-TESI22/solidjs/webco/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:52790:15)
    at ssrTransform (file:///E:/3-TESI22/solidjs/webco/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:52765:12)      
    at Object.ssrTransform (file:///E:/3-TESI22/solidjs/webco/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:61974:20)
    at loadAndTransform (file:///E:/3-TESI22/solidjs/webco/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36944:24)
GET http://localhost:8082/
An unhandled error occured: Error: Parse failure: Octal literal in strict mode (8:20)
Contents of line 8: import Root from "E:\3-TESI22\solidjs\webco\node_modules\solid-start\dev\CsrRoot.tsx";
    at ssrTransformScript (file:///E:/3-TESI22/solidjs/webco/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:52790:15)
    at ssrTransform (file:///E:/3-TESI22/solidjs/webco/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:52765:12)
    at Object.ssrTransform (file:///E:/3-TESI22/solidjs/webco/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:61974:20)
    at loadAndTransform (file:///E:/3-TESI22/solidjs/webco/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36944:24)

i have 

 node : v18.14.0
 npm :  8.1.1

I have CsrRoot.tsx :

import { Body, Html, Scripts } from "solid-start";

export default function Root() {
  return (
    <Html>
      <Body>
        <Scripts />
      </Body>
    </Html>
  );
}

**Comment by jean13360** [comment]
And only if i put false   ssr: false in vite.config.js

import solid from "solid-start/vite";
import { defineConfig } from "vite";
export default defineConfig({
  plugins: [
    solid({
      ssr: false,
    }),
  ],
});

**Comment by ryansolid** [comment]
Are you on windows? I think I broke windows paths with a recent commit.

**Comment by jean13360** [comment]
yep 👍

**Comment by ryansolid** [comment]
I made so.e windows fixes. Can you try 0.2.20?

**Comment by jean13360** [comment]
Thank you, it's ok now .
I will close the issue
