### ISSUE TITLE
Solid-Start with Storybook

### ISSUE THREAD

**Issue by madil4** [solidjs/solid-start#822]
Has anyone been able to run Storybook with Solid-Start? I've tried all the solutions provided here https://github.com/solidjs/solid-docs-next/issues/35, but none of them seem to work. These workouts are meant to be for solidjs, not solid-start

**Comment by ppecheux** [comment]
Hello, 
I am also looking for a solution to integrate storybook.
 For now, I just managed to launch storybook.
 I set up the .storybook/main.ts like that : 
```ts
import type { StorybookConfig } from "storybook-solidjs-vite";

const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "storybook-solidjs-vite",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
    });
  },
};

export default config
```
then I ran 

```sh
pnpm run storybook
```
but got following error at build time
```sh
> storybook dev -p 6006

@storybook/cli v7.0.6

info => Starting manager..
ERR! TypeError: Cannot read properties of null (reading 'once')
ERR!     at configureServer (file:///home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/solid-start@0.2.26_jjttyli7e42nw7nuih42omgpgm/node_modules/solid-start/vite/plugin.js:43:23)
ERR!     at _createServer (file:///home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/vite@4.3.1_@types+node@18.15.13/node_modules/vite/dist/node/chunks/dep-24daf00c.js:63404:30)
ERR!     at Module.start (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+builder-vite@7.0.6_mzhihm7zd2gyalpll4qoudvuha/node_modules/@storybook/builder-vite/dist/index.js:161:12571)
ERR!     at async storybookDevServer (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+core-server@7.0.6/node_modules/@storybook/core-server/dist/index.js:35:7062)
ERR!     at async buildDevStandalone (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+core-server@7.0.6/node_modules/@storybook/core-server/dist/index.js:48:2786)
ERR!     at async withTelemetry (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+core-server@7.0.6/node_modules/@storybook/core-server/dist/index.js:35:3422)
ERR!     at async dev (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+cli@7.0.6/node_modules/@storybook/cli/dist/generate.js:434:400)
ERR!     at async Command.<anonymous> (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+cli@7.0.6/node_modules/@storybook/cli/dist/generate.js:436:225)
ERR!  TypeError: Cannot read properties of null (reading 'once')
ERR!     at configureServer (file:///home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/solid-start@0.2.26_jjttyli7e42nw7nuih42omgpgm/node_modules/solid-start/vite/plugin.js:43:23)
ERR!     at _createServer (file:///home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/vite@4.3.1_@types+node@18.15.13/node_modules/vite/dist/node/chunks/dep-24daf00c.js:63404:30)
ERR!     at Module.start (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+builder-vite@7.0.6_mzhihm7zd2gyalpll4qoudvuha/node_modules/@storybook/builder-vite/dist/index.js:161:12571)
ERR!     at async storybookDevServer (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+core-server@7.0.6/node_modules/@storybook/core-server/dist/index.js:35:7062)
ERR!     at async buildDevStandalone (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+core-server@7.0.6/node_modules/@storybook/core-server/dist/index.js:48:2786)
ERR!     at async withTelemetry (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+core-server@7.0.6/node_modules/@storybook/core-server/dist/index.js:35:3422)
ERR!     at async dev (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+cli@7.0.6/node_modules/@storybook/cli/dist/generate.js:434:400)
ERR!     at async Command.<anonymous> (/home/pier/Documents/perso/skatelearning/poskills/jd-ssr/node_modules/.pnpm/@storybook+cli@7.0.6/node_modules/@storybook/cli/dist/generate.js:436:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```
I fixed this by modifying `node_modules/.pnpm/solid-start@0.2.26_jjttyli7e42nw7nuih42omgpgm/node_modules/solid-start/vite/plugin.js` like that 

```js
function solidStartInlineServerModules(options) {
  let lazy;
  let config;
  /** @type {import('vite').Plugin} */
  return {
    enforce: "pre",
    configResolved(_config) {
      lazy = _config.command !== "serve";
      config = _config;
    },
    name: "solid-start-inline-server-modules",
    configureServer(vite) {
      if (vite.httpServer) { // <--- here

        vite.httpServer.once("listening", async () => {
          const label = `  > Server modules: `;
          setTimeout(() => {
            if (vite.resolvedUrls) {
              const url = vite.resolvedUrls.local[0];
              // eslint-disable-next-line no-console
              console.log(`${label}\n   ${c.magenta(`${url}_m/*`)}\n`);
            }
          }, 200);
        });
      }
    }
  };
}

// [...]
    configureServer(vite) {
      server = vite;
      router.watch(console.log);
      router.listener = listener;
      if (vite.httpServer) { // <-- here
        vite.httpServer.once("listening", async () => {
          setTimeout(() => {
            if (vite.resolvedUrls) {
              const url = vite.resolvedUrls.local[0];
              // eslint-disable-next-line no-console
              printUrls(router, url.substring(0, url.length - 1));
            }
          }, 100);
        });
      }
    },

// [...]

```

Let me know if there is a cleaner way

**Comment by nksaraf** [comment]
Looks right! PRs welcome!

**Comment by kkharji** [comment]
Having issue with building a storybook. Any ideas why this is happening?

```
Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /home/develop/frontend/node_modules/.pnpm/solid-start@0.2.26_patch_hash=evoxgpefshtiwfjegzngcuqtbq_@solidjs+meta@0.28.5_@solidjs+router_irawurhyhfbuthxsarkzcboc7i/node_modules/solid-start/root/Document.tsx:48:28
46:       "body",
47:       props,
48:       () => (import.meta.env.START_SSR ? escape(props.children as string) : <Scripts />),
                                ^
49:       false
50:     ) as unknown as JSX.Element;
ERR! RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
ERR!     at error (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:2124:30)
ERR!     at Module.error (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:13463:16)
ERR!     at Module.tryParse (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:14184:25)
ERR!     at Module.setSource (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:13786:39)
ERR!     at ModuleLoader.addModuleSource (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:23782:20)
ERR!  Error [RollupError]: Unexpected token (Note that you need plugins to import files that are not JavaScript)
ERR!     at error (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:2124:30)
ERR!     at Module.error (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:13463:16)
ERR!     at Module.tryParse (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:14184:25)
ERR!     at Module.setSource (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:13786:39)
ERR!     at ModuleLoader.addModuleSource (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:23782:20) {
ERR!   cause: SyntaxError: Unexpected token (32:57)
ERR!       at pp$4.raise (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:21186:13)
ERR!       at pp$9.unexpected (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18487:8)
ERR!       at pp$9.semicolon (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18464:66)
ERR!       at pp$8.parseExpressionStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18947:8)
ERR!       at pp$8.parseStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18680:24)
ERR!       at pp$8.parseBlock (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18963:21)
ERR!       at pp$5.parseFunctionBody (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:21012:22)
ERR!       at pp$5.parseArrowExpression (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20973:8)
ERR!       at pp$5.parseParenArrowList (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20711:15)
ERR!       at pp$5.parseParenAndDistinguishExpression (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20677:19)
ERR!       at pp$5.parseExprAtom (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20529:41)
ERR!       at pp$5.parseExprSubscripts (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20362:19)
ERR!       at pp$5.parseMaybeUnary (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20328:17)
ERR!       at pp$5.parseExprOps (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20255:19)
ERR!       at pp$5.parseMaybeConditional (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20238:19)
ERR!       at pp$5.parseMaybeAssign (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20205:19)
ERR!       at pp$5.parseExprList (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:21065:18)
ERR!       at pp$5.parseSubscript (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20424:25)
ERR!       at pp$5.parseSubscripts (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20381:24)
ERR!       at pp$5.parseExprSubscripts (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20365:21)
ERR!       at pp$5.parseMaybeUnary (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20328:17)
ERR!       at pp$5.parseExprOps (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20255:19)
ERR!       at pp$5.parseMaybeConditional (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20238:19)
ERR!       at pp$5.parseMaybeAssign (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20205:19)
ERR!       at pp$5.parseExpression (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:20168:19)
ERR!       at pp$8.parseReturnStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18807:31)
ERR!       at pp$8.parseStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18635:37)
ERR!       at pp$8.parseBlock (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18963:21)
ERR!       at pp$8.parseStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18645:36)
ERR!       at pp$8.parseIfStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18792:26)
ERR!       at pp$8.parseStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18634:33)
ERR!       at pp$8.parseBlock (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18963:21)
ERR!       at pp$5.parseFunctionBody (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:21012:22)
ERR!       at pp$8.parseFunction (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:19085:8)
ERR!       at pp$8.parseFunctionStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18785:15)
ERR!       at pp$8.parseStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18630:17)
ERR!       at Parser.parseExport (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:25159:33)
ERR!       at pp$8.parseStatement (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18663:74)
ERR!       at pp$8.parseTopLevel (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18544:21)
ERR!       at Parser.parse (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18316:15)
ERR!       at Function.parse (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:18366:35)
ERR!       at Graph.contextParse (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:24866:38)
ERR!       at Module.tryParse (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:14181:31)
ERR!       at Module.setSource (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:13786:39)
ERR!       at ModuleLoader.addModuleSource (file:///home/develop/frontend/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:23782:20) {
ERR!     pos: 1605,
ERR!     loc: Position { line: 32, column: 57 },
ERR!     raisedAt: 1606
ERR!   },
ERR!   code: 'PARSE_ERROR',
ERR!   id: '/home/develop/frontend/node_modules/.pnpm/solid-start@0.2.26_patch_hash=evoxgpefshtiwfjegzngcuqtbq_@solidjs+meta@0.28.5_@solidjs+router_irawurhyhfbuthxsarkzcboc7i/node_modules/solid-start/root/Document.tsx',
ERR!   pos: 1605,
ERR!   loc: {
ERR!     column: 28,
ERR!     file: '/home/develop/frontend/node_modules/.pnpm/solid-start@0.2.26_patch_hash=evoxgpefshtiwfjegzngcuqtbq_@solidjs+meta@0.28.5_@solidjs+router_irawurhyhfbuthxsarkzcboc7i/node_modules/solid-start/root/Document.tsx',
ERR!     line: 48
ERR!   },
ERR!   frame: '46:       "body",\n' +
ERR!     '47:       props,\n' +
ERR!     '48:       () => (import.meta.env.START_SSR ? escape(props.children as string) : <Scripts />),\n' +
ERR!     '                                ^\n' +
ERR!     '49:       false\n' +
ERR!     '50:     ) as unknown as JSX.Element;',
ERR!   watchFiles: [
ERR!     '/home/develop/frontend/iframe.html',
ERR!     '/virtual:/@storybook/builder-vite/vite-app.js',
ERR!     '\x00vite/modulepreload-polyfill',
ERR!     '/virtual:/@storybook/builder-vite/setup-addons.js',
ERR!     '/virtual:/@storybook/builder-vite/storybook-stories.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/storybook-addon-breakpoints@1.0.0_@storybook+addons@6.5.16_@storybook+api@6.5.16_@storybook+c_nm3zcurj6hjccj7spxf5yruga4/node_modules/storybook-addon-breakpoints/dist/esm/preset/preview.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/storybook-addon-breakpoints@1.0.0_@storybook+addons@6.5.16_@storybook+api@6.5.16_@storybook+c_nm3zcurj6hjccj7spxf5yruga4/node_modules/storybook-addon-breakpoints/dist/esm/preset/addParameter.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/storybook-solidjs@1.0.0-beta.2_babel-preset-solid@1.7.4_solid-js@1.7.6/node_modules/storybook-solidjs/dist/config.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-links@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-links/dist/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-essentials@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/docs/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-essentials@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/actions/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-essentials@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/backgrounds/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-essentials@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/measure/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-essentials@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/outline/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-essentials@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-essentials/dist/highlight/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-interactions@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-interactions/dist/preview.mjs',
ERR!     '/home/develop/frontend/.storybook/preview.ts',
ERR!     '\x00vite/preload-helper',
ERR!     '/home/develop/frontend/node_modules/.pnpm/storybook-addon-breakpoints@1.0.0_@storybook+addons@6.5.16_@storybook+api@6.5.16_@storybook+c_nm3zcurj6hjccj7spxf5yruga4/node_modules/storybook-addon-breakpoints/dist/esm/withGlobals.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/storybook-solidjs@1.0.0-beta.2_babel-preset-solid@1.7.4_solid-js@1.7.6/node_modules/storybook-solidjs/dist/chunk-6VA2C2EE.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+docs-tools@7.1.1/node_modules/@storybook/docs-tools/dist/index.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-backgrounds@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-backgrounds/dist/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-docs@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-docs/dist/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-highlight@7.1.1/node_modules/@storybook/addon-highlight/dist/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-measure@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-measure/dist/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-outline@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-outline/dist/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/storybook-addon-breakpoints@1.0.0_@storybook+addons@6.5.16_@storybook+api@6.5.16_@storybook+c_nm3zcurj6hjccj7spxf5yruga4/node_modules/storybook-addon-breakpoints/dist/esm/breakpoints.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/storybook-addon-breakpoints@1.0.0_@storybook+addons@6.5.16_@storybook+api@6.5.16_@storybook+c_nm3zcurj6hjccj7spxf5yruga4/node_modules/storybook-addon-breakpoints/dist/esm/constants.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-actions@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-actions/dist/preview.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-mock@29.6.1/node_modules/jest-mock/build/index.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-interactions@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-interactions/dist/chunk-NNAAFZ4U.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+global@5.0.0/node_modules/@storybook/global/dist/index.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+instrumenter@7.1.1/node_modules/@storybook/instrumenter/dist/index.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-links@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-links/dist/chunk-VJY7NXNQ.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-links@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-links/dist/chunk-DXNAW7Q2.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-links@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-links/dist/chunk-JT3VIYBO.mjs',
ERR!     '/__uno.css',
ERR!     '/home/develop/frontend/package.json',
ERR!     '/home/develop/frontend/.storybook/viewports.ts',
ERR!     '/home/develop/frontend/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/mapValues.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/doctrine@3.0.0/node_modules/doctrine/lib/doctrine.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-docs@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-docs/dist/DocsRenderer-3PUGWF3O.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/solid-js@1.7.6/node_modules/solid-js/web/dist/web.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/solid-js@1.7.6/node_modules/solid-js/dist/solid.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/solid-js@1.7.6/node_modules/solid-js/store/dist/store.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/ts-dedent@2.2.0/node_modules/ts-dedent/esm/index.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-outline@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-outline/dist/chunk-2DMOCDBJ.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/index.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-actions@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-actions/dist/chunk-AY7I2SME.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-actions@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-actions/dist/chunk-VWCVBQ22.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/tiny-invariant@1.3.1/node_modules/tiny-invariant/dist/esm/tiny-invariant.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-measure@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-measure/dist/chunk-YIXVQKZ5.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-highlight@7.1.1/node_modules/@storybook/addon-highlight/dist/chunk-33ALZPRS.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+addon-backgrounds@7.1.1_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/addon-backgrounds/dist/chunk-GRJZJKJ4.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/@storybook+csf@0.1.1/node_modules/@storybook/csf/dist/index.mjs',
ERR!     '/home/develop/frontend/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/_baseAssignValue.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/_baseForOwn.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/_baseIteratee.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/doctrine@3.0.0/node_modules/doctrine/lib/typed.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/doctrine@3.0.0/node_modules/doctrine/lib/utility.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/esutils@2.0.3/node_modules/esutils/lib/utils.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/uuid@9.0.0/node_modules/uuid/dist/esm-browser/index.js',
ERR!     '/home/develop/frontend/src/routes/profile/edit.tsx',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/preRunMessage.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/specialChars.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/clearLine.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/createDirectory.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/ErrorWithStack.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/installCommonGlobals.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/interopRequireDefault.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/isInteractive.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/isPromise.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/setGlobal.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/deepCyclicCopy.js',
ERR!     '/home/develop/frontend/node_modules/.pnpm/jest-util@29.6.1/node_modules/jest-util/build/convertDescriptorToString.js',
ERR!     ... 470 more items
ERR!   ]
ERR! }
 ELIFECYCLE  Command failed with exit code 1.
zsh: exit 1     pnpm run build-storybook

```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
