### ISSUE TITLE
is hackernews-ts exemple run in default ?

### ISSUE THREAD

**Issue by electroheadfx** [solidjs/solid-start#83]
I got this error at build

```bash
$ npm run build

> build
> solid-start build

(node:8785) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
vite v2.7.13 building for production...
transforming (24) node_modules/solid-app-router/dist/integration.jsError when using sourcemap for reporting an error: Can't resolve original location of error.
✓ 30 modules transformed.
'innerHTML' is not exported by node_modules/solid-js/web/dist/web.js, imported by src/components/comment.tsx
file: /Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/components/comment.tsx:3:9
1: import { template as _$template } from "solid-js/web";
2: import { delegateEvents as _$delegateEvents } from "solid-js/web";
3: import { innerHTML as _$innerHTML } from "solid-js/web";
            ^
4: import { effect as _$effect } from "solid-js/web";
5: import { getNextElement as _$getNextElement } from "solid-js/web";
/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:160
        base = Object.assign(new Error(base.message), base);
                             ^

Error: 'innerHTML' is not exported by node_modules/solid-js/web/dist/web.js, imported by src/components/comment.tsx
    at error (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:160:30)
    at Module.error (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:12438:16)
    at Module.traceVariable (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:12808:29)
    at ModuleScope.findVariable (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:11601:39)
    at ReturnValueScope.findVariable (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:6964:38)
    at ChildScope.findVariable (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:6964:38)
    at ReturnValueScope.findVariable (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:6964:38)
    at ChildScope.findVariable (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:6964:38)
    at ReturnValueScope.findVariable (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:6964:38)
    at Identifier.bind (/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/rollup/dist/shared/rollup.js:6479:40) {
  code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  id: '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/components/comment.tsx',
  pos: 131,
  loc: {
    column: 9,
    file: '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/components/comment.tsx',
    line: 3
  },
  frame: '1: import { template as _$template } from "solid-js/web";\n' +
    '2: import { delegateEvents as _$delegateEvents } from "solid-js/web";\n' +
    '3: import { innerHTML as _$innerHTML } from "solid-js/web";\n' +
    '            ^\n' +
    '4: import { effect as _$effect } from "solid-js/web";\n' +
    '5: import { getNextElement as _$getNextElement } from "solid-js/web";',
  watchFiles: [
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/entry-client.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-js/web/package.json',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/package.json',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-js/web/dist/web.js',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/components/index.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/components/Links.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/components/Meta.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/components/Routes.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/components/Scripts.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/components/StartClient.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/components/StartContext.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/components/StartServer.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-js/package.json',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-js/dist/solid.js',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-app-router/package.json',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-app-router/dist/index.jsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/routes/[...stories].tsx?data',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/routes/stories/[id].tsx?data',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/routes/users/[id].tsx?data',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/routes/[...stories].tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/routes/stories/[id].tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/routes/users/[id].tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-meta/package.json',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-meta/dist/index.jsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/root.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/server/index.ts',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/components/story.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/components/comment.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/components/nav.tsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/src/root.css',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-app-router/dist/components.jsx',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-app-router/dist/integration.js',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-app-router/dist/routing.js',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-app-router/dist/utils.js',
    '/Users/efxair/Desktop/dev/solidtuts/hacker-news-solid-start/node_modules/solid-start/server/constants.js'
  ]
}
```

The npm run dev has some troubles too.

**Comment by ryansolid** [comment]
Looks like babel plugin out of sync with solid version. If both are on the latest this shouldn't be a problem.

**Comment by nksaraf** [comment]
Closing, assuming this worked for you @electroheadfx
