### ISSUE TITLE
[Bug?]: Dev server not running after creating from template

### ISSUE THREAD

**Issue by LanVukusic** [solidjs/solid-start#928]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm starting a solid-start project using a template `yarn create solid`. Choosing the tailwindcss option creates a project, but refuses to run, yielding an error
```
 version  0.2.26
failed to load config from /home/lan/Desktop/aprtma/vite.config.ts
file:///home/lan/Desktop/aprtma/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:66082
            throw new Error(`${e.message} at ${fileName}`);
                  ^

Error: The URL must be of scheme file at /home/lan/Desktop/aprtma/vite.config.ts
    at loadConfigFromBundledFile (file:///home/lan/Desktop/aprtma/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:66082:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async loadConfigFromFile (file:///home/lan/Desktop/aprtma/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:65931:28)
    at async Module.resolveConfig (file:///home/lan/Desktop/aprtma/node_modules/vite/dist/node/chunks/dep-1d3a4915.js:65535:28)
    at async resolveConfig (/home/lan/Desktop/aprtma/node_modules/solid-start/bin.cjs:522:16)
    at async /home/lan/Desktop/aprtma/node_modules/solid-start/bin.cjs:120:20
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Ubuntu linux 22
yarn 1.22.19  

### Expected behavior 🤔

Project should run a dev server.

### Steps to reproduce 🕹

Steps:

1. yarn create solid
2. select preset `with tailwindcss`
3. select using typescript
4. yarn
5. yarn run dev --open

### Context 🔦

I'm trying to create a new project. This bug makes this impossible.

### Your environment 🌎

```shell
System:
Ubuntu linux 22 
Intel i5 (x64)

Yarn 1.22.19
npm 8.11.0
```

**Comment by LanVukusic** [comment]
Figured out, that after switching from node version 16, to node version 18, the error is no longer present.
