### ISSUE TITLE
SSR issue with solidjs package built with "rollup-preset-solid"

### ISSUE THREAD

**Issue by aquaductape** [solidjs/solid-start#95]
I'm trying to use [solid-scroll-shadows](https://github.com/aquaductape/solid-scroll-shadows) package with SSR and it fails.

Here's the repo to replicate [https://github.com/aquaductape/test-scroll-shadows](https://github.com/aquaductape/test-scroll-shadows). File/Page where `solid-scroll-shadows` is being used [https://github.com/aquaductape/test-scroll-shadows/blob/main/src/routes/index.tsx](https://github.com/aquaductape/test-scroll-shadows/blob/main/src/routes/index.tsx)

I suspect it's a package output issue because I copied the library into the repo [https://github.com/aquaductape/test-scroll-shadows/tree/main/src/lib/solid-scroll-shadows](https://github.com/aquaductape/test-scroll-shadows/tree/main/src/lib/solid-scroll-shadows), and used it instead of using the official package and it works.
```js
// import ScrollShadows from "solid-scroll-shadows";
import ScrollShadows from "../lib/solid-scroll-shadows";
```

<details><summary>dev log "npm run dev"</summary>
<p>

```
2:29:28 AM [vite] Error when evaluating SSR module /src/routes/index.tsx:
file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/esm/index.js:1
import { template, effect, style, insert, createComponent, isServer, classList } from 'solid-js/web';
                                                                     ^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'classList'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56262:21)
    at async eval (/src/routes/index.tsx:19:31)
    at async instantiateModule (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:9)
2:29:28 AM [vite] Error when evaluating SSR module /node_modules/solid-start/root/Routes.tsx:
file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/esm/index.js:1
import { template, effect, style, insert, createComponent, isServer, classList } from 'solid-js/web';
                                                                     ^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'classList'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56262:21)
    at async eval (/src/routes/index.tsx:19:31)
    at async instantiateModule (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:9)
2:29:28 AM [vite] Error when evaluating SSR module /node_modules/solid-start/root/index.tsx:
file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/esm/index.js:1
import { template, effect, style, insert, createComponent, isServer, classList } from 'solid-js/web';
                                                                     ^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'classList'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56262:21)
    at async eval (/src/routes/index.tsx:19:31)
    at async instantiateModule (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:9)
2:29:28 AM [vite] Error when evaluating SSR module /src/root.tsx:
file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/esm/index.js:1
import { template, effect, style, insert, createComponent, isServer, classList } from 'solid-js/web';
                                                                     ^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'classList'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56262:21)
    at async eval (/src/routes/index.tsx:19:31)
    at async instantiateModule (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:9)
2:29:28 AM [vite] Error when evaluating SSR module /node_modules/solid-start/entry-server/StartServer.tsx:
file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/esm/index.js:1
import { template, effect, style, insert, createComponent, isServer, classList } from 'solid-js/web';
                                                                     ^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'classList'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56262:21)
    at async eval (/src/routes/index.tsx:19:31)
    at async instantiateModule (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:9)
2:29:28 AM [vite] Error when evaluating SSR module /node_modules/solid-start/entry-server/index.ts?v=ddf2b99f:
file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/esm/index.js:1
import { template, effect, style, insert, createComponent, isServer, classList } from 'solid-js/web';
                                                                     ^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'classList'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56262:21)
    at async eval (/src/routes/index.tsx:19:31)
    at async instantiateModule (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:9)
2:29:28 AM [vite] Error when evaluating SSR module /Users/caleb/Documents/just-programming/test-scroll-shadows/src/entry-server:
file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/esm/index.js:1
import { template, effect, style, insert, createComponent, isServer, classList } from 'solid-js/web';
                                                                     ^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'classList'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56262:21)
    at async eval (/src/routes/index.tsx:19:31)
    at async instantiateModule (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:9)
ERROR file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/esm/index.js:1
import { template, effect, style, insert, createComponent, isServer, classList } from 'solid-js/web';
                                                                     ^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'classList'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56262:21)
    at async eval (/src/routes/index.tsx:19:31)
    at async instantiateModule (/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:9)
```
</p>
</details>

<details><summary>build log "npm run build"</summary>
<p>

```
file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/rollup/dist/es/shared/rollup.js:1784
        base = Object.assign(new Error(base.message), base);
                             ^

Error: Could not resolve './components/ScrollShadows/ScrollShadows' from node_modules/solid-scroll-shadows/dist/source/index.jsx
    at error (file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/rollup/dist/es/shared/rollup.js:1784:30)
    at ModuleLoader.handleResolveId (file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/rollup/dist/es/shared/rollup.js:22285:24)
    at file:///Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/rollup/dist/es/shared/rollup.js:22248:26 {
  code: 'UNRESOLVED_IMPORT',
  watchFiles: [
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/.solid/server/index.js',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/dist/rmanifest.json',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/dist/manifest.json',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/.solid/server/app.js',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-start-node/server.js',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-start/runtime/prepareManifest.js',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-start/runtime/fetch.js',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/source/index.jsx',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-js/dist/server.js',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-js/web/dist/server.js',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/polka/build.mjs',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/sirv/build.mjs',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/compression/index.js',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/parse-multipart-data/dist/multipart.js',
    '\x00commonjsHelpers.js',
    '\x00/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/compression/index.js?commonjs-module',
    '\x00/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/parse-multipart-data/dist/multipart.js?commonjs-exports',
    '/Users/caleb/Documents/just-programming/test-scroll-shadows/node_modules/solid-scroll-shadows/dist/source/plugins/shadowMask.js'
  ]
}
```
</p>
</details>

**Comment by ryansolid** [comment]
My guess is this is another example of Vite SSR noExternal coming to bite us. It looks like you are getting the client compilation. It seems like we need to mark pretty much everything as no external so that it gets built.

**Comment by nksaraf** [comment]
Yeah we need to figure out how to warn the user about this.. maybe we can use the "solid" section in package json in some of these packages to inform us that they need to noExternal marked

**Comment by ryansolid** [comment]
Its funny because other frameworks have this problem too.. Sveltekit for one. I'd love to see if they got anywhere on this.

**Comment by nksaraf** [comment]
Closing this in favor of #127, will resolve both issues together
