### ISSUE TITLE
[Bug?]: (Astro version) Dev server crash after saving files

### ISSUE THREAD

**Issue by yume-chan** [solidjs/solid-start#951]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Yesterday I created a new Solid Start app with `pnpm create solid` and it gave me `"solid-start": "^0.3.0-alpha.7"`.

I tested it, but the dev server keeps crashing randomly after saving files.

Error stack:

```
file:///D:/dev/yume-chan/tango-web/node_modules/.pnpm/solid-start@0.3.0-alpha.7_@solidjs+meta@0.28.5_@solidjs+router@0.8.2_astro@2.9.1_solid-js@1.7.8_vite@4.4.6/node_modules/solid-start/vite/plugin.js:76
    timerState = "restart";
               ^

ReferenceError: timerState is not defined
    at Router.handleFileChange [as listener] (file:///D:/dev/yume-chan/tango-web/node_modules/.pnpm/solid-start@0.3.0-alpha.7_@solidjs+meta@0.28.5_@solidjs+router@0.8.2_astro@2.9.1_solid-js@1.7.8_vite@4.4.6/node_modules/solid-start/vite/plugin.js:76:16)
    at Router.notify (file:///D:/dev/yume-chan/tango-web/node_modules/.pnpm/solid-start@0.3.0-alpha.7_@solidjs+meta@0.28.5_@solidjs+router@0.8.2_astro@2.9.1_solid-js@1.7.8_vite@4.4.6/node_modules/solid-start/fs-router/router.js:90:27)
    at Router.processFile (file:///D:/dev/yume-chan/tango-web/node_modules/.pnpm/solid-start@0.3.0-alpha.7_@solidjs+meta@0.28.5_@solidjs+router@0.8.2_astro@2.9.1_solid-js@1.7.8_vite@4.4.6/node_modules/solid-start/fs-router/router.js:179:16)
    at FSWatcher.<anonymous> (file:///D:/dev/yume-chan/tango-web/node_modules/.pnpm/solid-start@0.3.0-alpha.7_@solidjs+meta@0.28.5_@solidjs+router@0.8.2_astro@2.9.1_solid-js@1.7.8_vite@4.4.6/node_modules/solid-start/fs-router/router.js:70:16)
    at FSWatcher.emit (node:events:514:28)
    at FSWatcher.emitWithAll (D:\dev\yume-chan\tango-web\node_modules\.pnpm\chokidar@3.5.3\node_modules\chokidar\index.js:541:32)
    at FSWatcher._emit (D:\dev\yume-chan\tango-web\node_modules\.pnpm\chokidar@3.5.3\node_modules\chokidar\index.js:632:8)
    at listener (D:\dev\yume-chan\tango-web\node_modules\.pnpm\chokidar@3.5.3\node_modules\chokidar\lib\nodefs-handler.js:370:20)
```

https://github.com/solidjs/solid-start/blob/cecd048b8bc8844f9660a8fdbbc9b3a35fe336b5/packages/start/vite/plugin.js#L76-L88

`timerState` is not defined and used anywhere.

### Expected behavior 🤔

No crash

### Steps to reproduce 🕹

Steps:

1. `npm run dev`
2. Edit some files
3. Ses the crash

### Your environment 🌎

```shell
Windows 11 x64
Node.js v18.17.0
```

**Comment by edivados** [comment]
> Yesterday I created a new Solid Start app with `pnpm create solid` and it gave me `"solid-start": "^0.3.0-alpha.7"`.

There was an issue with `create solid` using 0.3.0-alpha.7 instead of the latest 0.2.x version. This has already been fixed and `pnpm create solid` should give you the correct version again.

**Comment by yume-chan** [comment]
> There was an issue with `create solid` using 0.3.0-alpha.7 instead of the latest 0.2.x version. 

That's not the point of this issue. If this is the next version, you need to fix the code.
